erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
Firefox supports TURN, but Licode doesn't pass the TURN url.
I tested the change by running Licode on a remote server and adding a firewall rule to my machine to block outgoing IP packets from my machine to the remote Licode server, therefore forcing TURN.
The result of the test shows the following in about:webrtc (after this change - before, all candidates would fail):
Local candidate			 				Remote candidate
192.168.1.100:64140/udp(host)			10.176.5.159:41655/udp(host)   inprogress		
192.168.1.100:64140/udp(host)			REMOTE_IP:36724/udp(host)   failed		
TURN_ADD:64016/udp(relayed-udp)		 10.176.5.159:41655/udp(host)   inprogress		
TURN_ADD:64016/udp(relayed-udp)		 REMOTE_IP:36724/udp(host)   succeeded  *  *
=> Add TURN support for Firefox

erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/NiceConnection.h, erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h, erizo/src/erizo/media/ExternalInput.h, erizo/src/erizo/rtp/RtpSink.h, erizo/src/erizo/rtp/RtpSource.h
1. error: no template named 'scoped_ptr' in namespace 'boost'; did you
mean 'boost::asio::detail::scoped_ptr'
2. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:294:15:
error: read-only variable is not assignable
=> Fix build errors on Mac Yosemite

erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
As of Chrome 43, JSON.stringify no long works on RTCSessionDescription
and RTCIceCandidate objects and we need to expand them manually for
signaling. This change tested on Chrome 41 and Chrome 43.
Upstream bug: https://code.google.com/p/chromium/issues/detail?id=467471
=> RTC objects no longer act as POJSOs.

erizo/src/erizo/SdpInfo.cpp
For OPUS at least, the a=fmtp line looked like:
a=fmtp:111minptime=10
it lacks a space after the Codec number, and should look like:
a=fmtp:111 minptime=10
=> missing space in a=fmtp opus line

erizo_controller/erizoClient/src/webrtc-stacks/BowserStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeCanaryStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeRoapStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
When doing p2p audio only call, `spec.video` is undefined and gets set to true:
if (spec.video === undefined) {
spec.video = true;
}
This causes a crash in `setMaxBW` because sdp does not contain `m=video` media stream line.
var a = sdp.match(/m=video.*\r\n/);
if (a == null){
a = sdp.match(/m=video.*\n/);
}
// a is still null because sdp does not contain "m=video" line
var r = a[0] + "b=AS:" + spec.maxVideoBW + "\r\n";
sdp = sdp.replace(a[0], r);
=> This fixes exception in setMaxBW when doing p2p audio only call

scripts/installMacDeps.sh
Fix for this warning:
```
Installing homebrew... [press Enter]
Whoops, the Homebrew installer has moved! Please instead run:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Also, please ask wherever you got this link from to update it to the above.
Thanks!
```
=> Update Homebrew installation URL for Mac dependency script because it has moved

erizo/src/erizo/SdpInfo.cpp
The fix is to simply change the 4 to a 3 so that the conditional code to add the BundleTag objects to the bundleTags vector.  Credit to Jeremy Noring on the lynckia google group for finding this fix.
In the case of video-only `a=group:BUNDLE video` or audio-only `a=group:BUNDLE audio`, the number of parts is only 3.  Without the bundle tags, the remote description had an invalid bundle definition `a=group:BUNDLE`.  Most of the time with WebRTC the bundle definition will be `a=group:BUNDLE audio video` for audio and video streaming.
This fixes video-only and audio-only streaming in Chrome 47. issue #375
=> fix sdp offer bundle parsing when streaming video-only or audio-only

erizo_controller/erizoClient/src/Room.js
if p2p = true the peerconnection was not closed causing high network traffic and high cpu load.
=> BugFix unpublish in p2p

erizo_controller/erizoAgent/erizoAgent.js
Automatically get the publicIp if global.config.cloudProvider.name = 'amazon' thanks to aws-lib. (same as in cloudHandler.js)
Useful to for single erizoAgent processes deployed to the cloud
=> erizoAgent AWS public ip

package.json
$ npm install
npm WARN package.json licode@0.1.0 No repository field.
npm WARN package.json licode@0.1.0 No license field.
license was set to 'MIT' and the package was marked private to eliminate warnings from npm
=> fix for npm warnings regarding license and repository

erizo_controller/erizoController/erizoController.js, scripts/licode_default.js
adds the following keys to licode_config.js
- config.erizoController.ssl_key
- config.erizoController.ssl_cert
allows specifying a custom location for SSL key/cert
=> custom location for SSL creds

erizo_controller/erizoAgent/erizoAgent.js, scripts/licode_default.js
Used to declare the log file location for spawned erizo instances.
Allows erizoAgent to more easily be run as non-root user.
=> provide config.erizoAgent.instanceLogDir

erizo/README.md
- Fix typo error 'y' -> 'j' in __Build Instructions__
=> Fix typo in erizo/README.md

erizo_controller/erizoClient/src/Stream.js
Local streams currently get an undefined ID in getID().
=> Provide valid ID for local stream

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h
Fix a memory leak in ExternalOutput which appear when the frame dimensions are bigger than buffer (especially when resolution > 640 x 480)
The frames are now dropped, preventing erizoJs to crash.
=> Fix memory leak ExternalOutput

scripts/installErizo.sh
Since many of us use Node Version Manager to switch between different versions of node, it would be helpful to show a warning if we're using the wrong version of node to compile Erizo.
=> Add a warning when using an unsupported version of node for Erizo

nuve/installNuve.sh
The mongojs lib was updated from 2.3.0 -> 2.4.0 which uses some features like object.assign which are not supported by 0.10.x.
I would suggest making a proper package.json file for all the needed libs. Its actually quite brittle the way it is now.
=> urgent: fix for mongojs installed which not compatible with node 0.10.x

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/NiceConnection.cpp, erizo/src/erizo/NiceConnection.h, erizo/src/erizo/Transport.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo_controller/erizoAgent/log4cxx.properties
WebRtcConnection, NiceConnection and DtlsTransport logs now include a connection identifier.
Logs are a bit cleaner now, with a more unified format in these 3 classes.
OneToMany logs will be introduced in another PR
=> Provide connection context in logs

erizo/src/erizo/WebRtcConnection.cpp
There's a race condition that can cause Erizo to crash, this should avoid the crash. Should still keep an eye for the race condition
=> Added check for null transport when adding candidates

erizo_controller/common/amqper.js, erizo_controller/common/logger.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js
Objects are now capped to be logged at 1 level, with the standard "key: value, key2: value2" format.
Removed all logs using ","  - switched to "+" instead to prevent accidentally logging large objects
=> Added utility log function - used it to log objects throughout

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/dtls/DtlsClient.cpp, erizo/src/erizo/dtls/DtlsSocket.h
Changed Resender to make it easier to send multiple resends with the same object and set a limit for the max amount of resends. Going over that limit will trigger a TRANSPORT_FAIL
=> Resender now works directly through the DtlsTransport and has a max amount of resends

nuve/nuveAPI/rpc/rpc.js
A new callback was introduced in PR #567, this broke nuve.js
=> Fixed Nuve crash because of missing callback

erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/views/AudioPlayer.js, erizo_controller/erizoClient/src/views/VideoPlayer.js
current code assumes that the element to attach the player to already exists
in the DOM, however, many new frameworks allow manipulating DOM trees prior
to DOM insertion. this patch allows the show/play methods to accept a DOM
node as well as a string identifier.
=> allow DOM node to be passed to show/play method

erizo_controller/erizoClient/src/views/AudioPlayer.js, erizo_controller/erizoClient/src/views/VideoPlayer.js
This adds a 'label' and 'bar' key to the options arg for Erizo.Stream.show()
This allows:
- The same stream to be placed in multiple elements on the page using a
custom label for each invocation of stream.show(), eg {label: 'foo'}
- The bottom bar to not be rendered if {bar: false} is passed. In this
case, a 'media' prop is set on the stream object, to provide a
consistent interface to the underlying audio or video object.
It does create the side effect of multiple independent bar controls
=> add label/bar options for showing streams.

.gitignore, erizo/src/test/NiceConnectionTest.cpp, erizo/src/test/PacketTest.cpp
Just a couple of minor fixes that should make Licode life cleaner
=> Fix/minor cometic fixes: media config file to gitignore and compilation warnings

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/NiceConnection.cpp, erizo/src/erizo/NiceConnection.h, erizo/src/erizo/Transport.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/logger.h, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, extras/basic_example/public/script.js
With this change both publish() and subscribe() methods in clients will accept a new field in options called metadata. 
Metadata is an Object with keys and values, both should be strings. Below you can find an example:
```
{metadata: {type: 'publisher', external_id: 'id1'}}
```
All fields inside metadata will be printed in logs in Erizo in this PR. And we will add them to ErizoController logs too.
=> Add the possibity to include metadata in the logs

erizo/src/erizo/SdpInfo.cpp
We were including a=maxptime:60 it is legacy code
=> Removed maxptime as it no longer makes sense here

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/thread/ThreadPool.cpp, erizo/src/erizo/thread/ThreadPool.h, erizo/src/erizo/thread/Worker.cpp, erizo/src/erizo/thread/Worker.h, erizo/src/test/rtp/RtpRetransmissionHandlerTest.cpp, erizoAPI/ThreadPool.cc, erizoAPI/ThreadPool.h, erizoAPI/WebRtcConnection.cc, erizoAPI/addon.cc, erizoAPI/binding.gyp, erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js, scripts/licode_default.js, spine/nativeClient.js
This PR sets a ThreadPool that will be used to get Workers and assign them to WebRtcConnections. These workers will be threads processing RTP packets, but they won't do IO tasks.
I've added a new parameter in the configuration called numWorkers, that is the total number of threads that will be used by Erizo to process RTP packets.
=> Add a ThreadPool for WebRtcConnections

erizo_controller/erizoAgent/erizoAgent.js, nuve/installNuve.sh, nuve/nuveAPI/cloudHandler.js, scripts/licode_default.js
related to: https://github.com/ging/licode/pull/445
I decided to switch from aws-lib to aws-sdk (which is the official one I think).
Anyway, it appears that using AWS.Metadata we are able to obtain our public ip from amazon without the need to create an IAM role and hardcode our public / secret aws keys in our code and without specify the region.
rapidly tested and seems working.
=> Replaced aws-lib with aws-sdk

scripts/rtp_media_config_default.js
in Chrome
From [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/BqqFMSR6s1E/rlPYFD0NCQAJ)
=> Removed 'transport-cc' to disable sender side-only bandwidth estimation

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h
I've changed the initialization of the FEC Receiver by using the new API and I've tested it locally several times successfully.
@kekkokk can you check if this PR fixes #658 please? I think the real issue arose when I updated webrtc library because I didn't change this code.
=> Fixes a crash in ExternalOutput even when we don't use FEC/RED

erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo/src/erizo/rtp/RtpHeaders.h, erizo/src/test/rtp/BandwidthEstimationHandlerTest.cpp
This PR fixes some issues with slow REMB ramp up and removes some warnings.
=> Fix REMB estimator in Erizo to improve initial ramp up

extras/basic_example/basicServer.js, nuve/nuveAPI/cloudHandler.js, nuve/nuveAPI/resource/roomResource.js, nuve/nuveAPI/resource/roomsResource.js, nuve/nuveAPI/resource/serviceResource.js, nuve/nuveAPI/resource/servicesResource.js, nuve/nuveAPI/resource/tokensResource.js, nuve/nuveAPI/resource/userResource.js, nuve/nuveAPI/resource/usersResource.js, nuve/nuveAPI/test/resource/usersResource.js, nuve/nuveClient/src/N.API.js
When Cloud Handler receives a timeout when checking users in a room, the response is now correctly handled in Nuve Client.
This fixes a break in basic example when removing old rooms.
I've also updated status responses in nuve to new express notation.
=> Fixes when checking users from Cloud Handler to Erizo Controller

erizo/src/erizo/rtp/RtpAudioMuteHandler.cpp, erizo/src/erizo/rtp/RtpAudioMuteHandler.h, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/erizoJS/erizoJSController.js, erizo_controller/test/utils.js
This PR aims to:
With this PR we can mute audio from Publisher and it will stop sending bytes to all the subscribers, saving bandwidth in these cases.
=> Enable client API to mute audio on publishers

erizo/src/erizo/Stats.cpp, erizo/src/erizo/Stats.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/permission.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, scripts/licode_default.js
ErizoClient can be used to access real-time stats gathered directly by Erizo. They contain mostly from RTCP packets from the clients but also a couple of Erizo-calculated values: actual bitrates and the output from the Erizo bitrate estimator.
The API may change but for now they are accessed with:
`room.getStreamStats(streamID, callback)` where the callback takes one parameter, the actual stats data in JSON format.
Also, this PR introduces a new _permission_:`STATS` that can be used to limit which roles can access the stats.
=> Added client-side API to access stats from Erizo

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/pipeline/Handler.h, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo/src/erizo/rtp/RtpAudioMuteHandler.cpp, erizo/src/erizo/rtp/RtpAudioMuteHandler.h, erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp, erizo/src/erizo/rtp/RtpRetransmissionHandler.h, erizo/src/erizo/rtp/RtpSlideShowHandler.h, erizo/src/erizo/rtp/RtpVP8SlideShowHandler.cpp, erizo/src/erizo/rtp/RtpVP8SlideShowHandler.h, erizo/src/test/rtp/BandwidthEstimationHandlerTest.cpp, erizo/src/test/rtp/RtpAudioMuteHandlerTest.cpp, erizo/src/test/rtp/RtpRetransmissionHandlerTest.cpp, erizo/src/test/rtp/RtpVP8SlideShowHandlerTest.cpp, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, scripts/licode_default.js
With this PR we'll be able to disable handlers (and functionality) by default in Erizo. 
Each handler will now use a unique name to be identified and we can disable them with a line like this one in licode_config.js :
```js 
config.erizo['disabled_handlers'] = ['bwe', 'retransmissions'];
```
=> Handlers con now be disabled by configuration

erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/RtpExtensionProcessor.cpp, erizo/src/erizo/rtp/RtpExtensionProcessor.h, erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/test/erizoAgent/erizoAgent.js, erizo_controller/test/utils.js
There are two issues fixed here:
- We were not properly handling transport-cc extensions internally.
- We were not piping error messages from ErizoJS processes to the single log file.
=> Add support to Transport CC header extensions

erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js
This PR makes create offer parameters (audio, video and bundle) configurable when publishing a stream. 
The Erizo Client API has an small change: 
- Before
`room.publish(stream, { createOffer: true });`
- Now
`room.publish(stream, { createOffer: {audio: true, video: true, bundle: true} );`
=> Adding parameters to create offer when publishing

erizo/src/erizo/NiceConnection.cpp, erizo/src/erizo/NiceConnection.h, erizo/src/erizo/lib/LibNiceInterface.h, erizo/src/erizo/lib/LibNiceInterfaceImpl.cpp, erizo/src/test/NiceConnectionTest.cpp, erizoAPI/WebRtcConnection.cc, erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, scripts/licode_default.js
Not needed to merge this now, it's something I've needed during the latest weeks to run Licode inside Vagrant using multiple interfaces. 
The reason to add it it that it might be needed in some cases, especially when servers have multiple network interfaces.
=> Give the option to choose which network interface we will bind services

erizo_controller/erizoJS/erizoJSController.js
By passing a period in milliseconds instead of `true` to the slideShowMode option from erizoClient, you can now adjust the slideShow frame rate.
=> SlideshowMode can be configured at different periods now

erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/RtpExtensionProcessor.cpp, erizo/src/erizo/rtp/RtpExtensionProcessor.h, erizo/src/test/rtp/RtpExtensionProcessorTest.cpp, erizo/src/test/utils/Mocks.h, erizoAPI/WebRtcConnection.cc, scripts/rtp_media_config_default.js
With this PR we need to provide a list of supported extensions via rtp_media_config.js.
It will disable transport-cc by default to keep using REMB and abs-send-time in Chrome 55, which is a bug we found today.
=> Added extension mappings to media config file

erizoAPI/WebRtcConnection.cc
Risky casting from `int16_t` to `unsigned int` was causing problems compiling in mac
=> value should be unsigned int for consistency

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/pipeline/Handler.h, erizo/src/erizo/pipeline/HandlerContext-inl.h, erizo/src/erizo/pipeline/Pipeline.cpp, erizo/src/erizo/pipeline/Pipeline.h, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo/src/erizo/rtp/FecReceiverHandler.cpp, erizo/src/erizo/rtp/FecReceiverHandler.h, erizo/src/erizo/rtp/RtcpProcessorHandler.cpp, erizo/src/erizo/rtp/RtcpProcessorHandler.h, erizo/src/erizo/rtp/RtpAudioMuteHandler.cpp, erizo/src/erizo/rtp/RtpAudioMuteHandler.h, erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp, erizo/src/erizo/rtp/RtpRetransmissionHandler.h, erizo/src/erizo/rtp/RtpSlideShowHandler.h, erizo/src/erizo/rtp/RtpVP8SlideShowHandler.cpp, erizo/src/erizo/rtp/RtpVP8SlideShowHandler.h, erizo/src/erizo/rtp/StatsHandler.cpp, erizo/src/erizo/rtp/StatsHandler.h, erizo/src/test/rtp/BandwidthEstimationHandlerTest.cpp, erizo/src/test/utils/Mocks.h
Implementing new handlers should be quite easier with this PR. All calls from WebRtcConnection will be synced with the worker thread, so it will reduce the need of mutex or similar control structures.
I've also remove the need of having another list by using Pipeline as the proxy to call handlers.
=> Update handlers interface to avoid mutex and external lists

erizo/src/erizo/rtp/RtpExtensionProcessor.cpp
When switching to monotonic clock, we introduced a bug here where abs_send_time was not being calculated properly.
This affected cc estimation for receivers.
This should fix #718
=> Fixed use of monotonic clock in abs_send_time rewrite

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
If no video/audio option is specified when subscribing to a stream, we need to check if the subscribed stream has video/audio and construct the local SDP accordingly.
=> Fixed a bug when subscribing to only audio stream in Chrome

erizo/src/erizo/MediaDefinitions.h
This could cause problems if we generate packets in the middle of the pipeline, as the `received_time_value_ms` was only being written in `NiceConnection`
=> Added initialization of dataPacket with current clock

erizo_controller/erizoClient/src/Room.js
ATM, in a p2p call, if you unsubscribe to a stream and you try to re-subscribe you will get an error.
=> [BUGFIX] delete old peerConnection.

erizo/src/erizo/rtp/RtcpProcessorHandler.cpp
RtcpProcessorHandler was dropping all non-feedback RTCP Packets (mostly SR)
=> Fixed rtcpProcessorHandler incorrectly dropping SR

erizo/src/erizo/Stats.cpp, erizo/src/erizo/rtp/StatsHandler.cpp
Stats was incorrectly analyzing SR packets as RTP:
I've taken into account that RTCP should now be analyzed on write also. In this case, failing the SSRC checks does not mean the SSRC is unknown, it means that we don't want to account for that packet in that part of the path, thus I've removed the log message.
=> Fixed SR stats in the subscriber

erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo_controller/erizoAgent/log4cxx.properties, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js
The functionality for disabling handlers by default was broken before this PR because we moved the initialization of the pipeline to the moment when we receive a remote SDP. I've also fixed BWE logs.
=> Fix disable default handlers

erizo/src/erizo/WebRtcConnection.cpp
Currently `updateConfiguration({maxVideoBW: value})` will trigger a new `setRemoteSdp` in `WebRtcConnection` which may cause trouble with the way the pipeline is initialized now.
I've limited the things that can be done in any renegotiation for now until we decide how much we want to be able to renegotiate.
=> Avoid reinitializing pipeline and other things on a setMaxBW

erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h, erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.h, erizo/src/test/rtp/SequenceNumberTranslatorTest.cpp
With this new translator we should be able to seamlessly send packets that belong to different temporal and spatial layers in SVC and temporal layers in Simulcast.
=> Add a new Sequence Number translator for Simulcast/SVC

erizo/src/erizo/NiceConnection.cpp, erizo/src/erizo/NiceConnection.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h
It adds more information to the stats and logs, to know the client and erizo candidate Host Type (server reflexive, host, peer reflexive or relay).
There's no change in the public APIs.
=> Add selected client candidate host type to logs and stats

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.h
It adds timestamp translation when switching SSRCs in Chrome's Simulcast. It also fixes a couple of minor bugs in the QualityFilter.
=> Fix quality filter with timestamp switching

erizo/src/erizo/rtp/RtcpNackGenerator.cpp
Fixes a crash in `RtcpNackGenerator`. I did not update the index properly after erasing an element in the nack vector,  causing out of bounds problems.
Noooop
=> fixed crash in nackGeneration because of an out of bounds index

erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/test/rtp/SequenceNumberTranslatorTest.cpp
This PR fixes an issue in SequenceNumberTranslator when there are several loops of sequence numbers in total. I added a Unit Test to cover this case too.
No needed.
=> Fix several loops in SequenceNumberTranslator

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.h
We now drop feedback packets when Simulcast/SVC is enabled. But we still send PLIs when we receive them in Erizo.
No change.
=> Terminate RTCP Feedback in Scalable Video

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h
We now remove padding bytes (or entire packets if there is no payload data) to save bandwidth in the subscribers.
Not needed.
=> Add a mechanism to drop padding bytes and packets

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/erizo/rtp/RtcpAggregator.cpp, erizo/src/erizo/rtp/RtcpAggregator.h, erizo/src/erizo/rtp/RtcpForwarder.cpp, erizo/src/erizo/rtp/RtcpForwarder.h, erizo/src/erizo/rtp/RtcpProcessor.h, erizo/src/erizo/rtp/RtpHeaders.h, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h, erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.h, erizo/src/test/log4cxx.properties, erizo/src/test/rtp/RtpPaddingGeneratorHandlerTest.cpp, erizo/src/test/rtp/SequenceNumberTranslatorTest.cpp, erizo/src/test/utils/Mocks.h, erizo/src/test/utils/Tools.h, erizo_controller/erizoAgent/log4cxx.properties
As part of Simulcast/SVC it adds a new handler to generate padding. It will be useful when we need to increase bitrates and sender bandwidth estimations. 
Not needed.
=> Add a padding generator handler

erizo_controller/erizoClient/src/Room.js
It adds the possibility to set a Maximum Video Bandwidth from the subscribers.
I didn't update the docs because it was already there and we made no distinction between publisher and subscriber.
=> Add the option to update the max video bw in the subscriber

erizo/src/erizo/OneToManyProcessor.cpp
Adds a nullptr check to avoid having crashes in Erizo. Fixes #793 
Not needed
=> Add nullptr check when delivering audio

erizo/src/erizo/rtp/QualityFilterHandler.cpp
Fix Quality Filter Handler to take into account packets from other spatial layers during SeqNum translation.
Not needed.
=> Fix bad quality filter behaviour with VP9 SVC

extras/basic_example/basicServer.js, extras/basic_example/public/script.js
Now you can specify the room type when dynamically creating rooms in basic example. Connecting to `https://basic_server:3004/?room=1234&type=p2p` creates a p2p room called '1234'.
No changes
=> Added the possibility of dynamically creating p2p rooms in basic example

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h, erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp, erizo/src/erizo/rtp/RtpRetransmissionHandler.h, erizo/src/test/rtp/QualityManagerTest.cpp
Added more stats:
- rtxBitrate: Bitrate generated by erizo retransmissions to subscribers
- paddingBitrate: The bitrate generated by padding in simucast
- selected[Temporal | Spatial]Layer
- maxActive[Temporal | Spatial]Layer
=> Add more stats 

erizo_controller/erizoAgent/log4cxx.properties, extras/basic_example/basicServer.js, extras/basic_example/public/quality_layers.js
Add a new option to quality layers to load info from a known room Id.
Not needed.
=> Add RoomId option to quality layers

erizo/src/erizo/WebRtcConnection.cpp
Check if the WebRTCConnection is ready before sending packets to the pipeline
=> Fix - put packets in pipeline only when ready

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/erizo/rtp/SequenceNumberTranslator.h, erizo/src/test/rtp/SequenceNumberTranslatorTest.cpp
This PR fixes cases where we are resetting the sequence number translator without having received no more than skipped packets.
It adds more tests to SequenceNumberTranslatorTest.cpp
Not needed.
=> Fix wrong reset in SeqNum Translator

.jshintignore, .jshintrc, erizo_controller/erizoClient/src/Connection.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FcStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/erizoJS/erizoJSController.js, extras/basic_example/basicServer.js, extras/basic_example/public/quality_layers.js, nuve/nuveAPI/mdb/roomRegistry.js, scripts/licode_default.js
This PR fixes jshint issues
None
=> Fixed jshint

erizo/src/erizo/rtp/SequenceNumberTranslator.cpp, erizo/src/test/rtp/SequenceNumberTranslatorTest.cpp
The previous PR did not solve the issue completely and it introduce some wrong behavior in the padding generator. I fixed unit tests and the bug itself here.
Not needed
=> Fixes unit tests and bad sequence number translations

erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h
Disable padding when max layer is 0/0 to avoid introducing padding when there is no simulcast/svc.
Also added a utility method to enable/disable padding
=> Disable padding when max layer is 0/0

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/test/rtp/QualityManagerTest.cpp, erizo/src/test/utils/Tools.h
The `QualityManager` will now be disabled by default (and padding also), until `QualityFilterHandler` detects the first packet of an scalable layer. 
=> QualityManager will be disabled unless is_scalable

scripts/initBasicExample.sh, scripts/initLicode.sh
Now nuve and erizoClient dist scripts are copied to basic example when running its initialization script
none
=> Copying nuve and erizoClient dist files in initBasicExample script

erizo/src/test/rtp/RtcpRrGeneratorTest.cpp
Fixes the random failures of RtcpRrGeneratorTest.shouldReportDelaySinceLastSr
=> Fixed test

.travis.yml, erizo/src/erizo/rtp/RtpSlideShowHandler.cpp, nuve/installNuve.sh, nuve/nuveClient/tools/compile.sh, nuve/nuveClient/tools/compileDist.sh
Fixes an issue when installing NuveClient because we still used Java, which is a removed dependency.
Not needed.
=> Avoid using java in nuveClient installation

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/NiceConnection.cpp, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/dtls/DtlsClient.cpp, erizo/src/erizo/dtls/DtlsSocket.cpp, erizo/src/erizo/dtls/DtlsSocket.h, erizoAPI/OneToManyProcessor.cc
Fix some crashes when deleting WebRtcConnections. It uses WebRtcConnection's thread to close it.
Not needed.
=> Fix a crash when deleting WebRtcConnection

erizo/src/erizo/rtp/PliPacerHandler.h, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/test/rtp/PliPacerHandlerTest.cpp
Increases the timeout for sending PLIs and it avoids sending multiple PLIs in the Quality Filter because we now rely on the PLI pacer.
None.
=> Fix PLI sending rates

erizo/src/erizo/lib/LibNiceInterfaceImpl.cpp, scripts/installUbuntuDeps.sh, scripts/libnice-014.patch0
We've found more ICE failures happening with v0.1.7 so we'll revert version 0.1.4 temporarily while we discuss a better approach for handling ICE (update to latest versions or even switch to another library).
Not needed.
=> Revert libnice to version 0.1.4 temporarily

erizo/src/erizo/WebRtcConnection.cpp
testing the current branch, I noticed that firefox won't publish in audio only mode. digging into the code i found this "return" statement if the video transport wasn't specified. 
Resolved adding another check but don't know if it's ok.
Tell me what do you think.
Probably needs but doesn't include
=> candidates won’t be added when Firefox in audio publish only.

erizo_controller/erizoController/erizoController.js
Stream status was not set to PUBLISHER_READY causing erizo controller not include the stream on the stream list after a room connection, causing clients not being able to subscribe if they weren't already on the room.
It needs but doesn't include, couldn't find erizo controller tests checking PUBLISHER_READY status in other scenarios, I guess it's the way the RPC calls are tested that makes it complex to test?. Also would be helpful a mini-guide about how to run the full test suite, or just some components. I am running them as I figured out but I am sure there is better way to do it.
No public API changes.
=> fix stream status after successfuly adding external input

scripts/installMacDeps.sh, scripts/travisInstallDeps.sh
Also revert to libnice 0.1.4 in Mac and Travis.
Not needed.
=> Revert to libnice 0.1.4 also in Mac and Travis

erizo/src/erizo/media/ExternalOutput.cpp
Fix ExternalOutput with Simulcast. It now gets the lower quality layer, which is sub-optimal. But having a better solution would involve:
- Implement a pipeline in ExternalOutput to detect quality layers and filter packets.
- Connect two ErizoJS (one acting as a pure MCU and another recording the stream).
Not needed.
=> Fix ExternalOutput with Simulcast

erizo/src/erizo/stats/StatNode.cpp, erizo/src/test/stats/MovingAverageStatTest.cpp
- fixed MovingAverageStat when value < old_value
- +0.1 when casting _current_average to uint64, to avoid 3.999... -> 3
- added some test cases for MovingAverageStat
=> fixed MovingAverageStat when value < old_value

README.md, doc/custom_theme/nav.html
Updated the Readme.md file and removed the `installation` tab in the nav bar as it is redundant now.
*Add a detailed description of any change in the public APIs.*
=> Fixed Readme and nav bar in docs

erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
Removed the alert/warning that shows up every time we publish a simulcast stream.
Not needed.
=> Remove Simulcast WIP message

erizo_controller/erizoClient/src/Connection.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
This PR adds support for Electron screensharing. Electron does not have to use an extension like Chrome does.
No changes in the API, it should work transparently.
=> Add support for Electron screensharing

scripts/travisScript.sh
Now when linter fails, travis script exits.
=> Minor change to fix travis script

erizo_controller/erizoController/erizoController.js
Fix an erizo controller crash when requesting stats from a p2p room
=> fix a crash when requesting stream stats in a p2p room

scripts/installUbuntuDeps.sh
Remove a wrong script command, which is harmless but makes it hardest to understand.
Not needed. 
=> Remove wrong script command

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/pipeline/Handler.h, erizo/src/erizo/pipeline/HandlerContext-inl.h, erizo/src/erizo/pipeline/Pipeline.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/FecReceiverHandler.cpp, erizo/src/erizo/rtp/LayerBitrateCalculationHandler.cpp, erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/PliPacerHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/RtcpFeedbackGenerationHandler.cpp, erizo/src/erizo/rtp/RtcpProcessorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingRemovalHandler.cpp, erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp, erizo/src/erizo/rtp/RtpSlideShowHandler.cpp, erizo/src/erizo/rtp/RtpTrackMuteHandler.cpp, erizo/src/erizo/rtp/RtpTrackMuteHandler.h, erizo/src/erizo/rtp/SRPacketHandler.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/erizo/rtp/StatsHandler.cpp
Slight optimization in the RTP packet's hot path, by better handling shared pointers to avoid creating/removing them too much.
Not needed.
=> Slight optimization in the packet's hot path

spine/nativeClient.js, spine/runSpineClients.js, spine/simpleNativeConnection.js
Add info about subscriptions to Spine. It will show how many subscribers are connected or not every few seconds (it's configurable).
Not needed. 
=> Add connectivity stats to spine

erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp
Fixes #938 
Thanks to @kekkokk for the heads up. Turned out to be that Chrome is sending REMB packets within compound audio RR. And they can sometimes have a SSRC different from video's. [1]
Not needed.
[1] https://bugs.chromium.org/p/webrtc/issues/detail?id=7860
=> Fix wrong REMB detection with Chrome 60

erizo_controller/erizoClient/src/Connection.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/utils/L.Resizer.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FcStack.js
Add default functions to callbacks passed as arguments to Erizo Client API.
Not needed.
=> Add default functions to callbacks in Erizo Client

scripts/installMacDeps.sh, scripts/installUbuntuDeps.sh, scripts/travisInstallDeps.sh
Following command in [installUbuntuDeps.sh](https://github.com/lynckia/licode/blob/master/scripts/installUbuntuDeps.sh#L137-L138) returns "gzip: stdin: not in gzip format" because opus-1.1.tar.gz has been redirected to other location.
```
curl -O http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
tar -zxvf opus-1.1.tar.gz
```
**Changes**
I changed "curl -O http://xxx" to "curl -OL http://xxx"  in all installXXX.sh files.
=> Added location curl option

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo/src/test/rtp/BandwidthEstimationHandlerTest.cpp
Cap the maximum bitrate sent in the REMBs generated by the sender bitrate estimator, with the value obtained in the SDP.
Not needed.
=> Cap max bitrate in sender bwe

.circleci/config.yml, Dockerfile, erizo/buildProject.sh, scripts/installErizo.sh, scripts/installUbuntuDeps.sh
Adds support to Circle CI 2.0
Not needed.
=> Add support to CircleCI

.circleci/config.yml, .dockerignore, utils/release.sh
`docker push` does not accept multiple tags in the same command.
=> Fix docker push with multiple tags

scripts/initBasicExample.sh
This PR fixes a bug that rewrote erizo.js file if you had an old compiled version 
=> Avoiding rewriting old erizo.js when launching basic example

erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
We were not able to subscribe with {audio:true, video:false} to a stream published as {audio:true, video:false}. There were similar issues that this PR fixes.
Fixes #985 
Not needed.
=> Fix issues with audio only streams.

erizo_controller/erizoClient/webpack.config.erizo.js
Enabled the generation of source maps for erizo when creating the bundle. In order to debug Licode, you can use the `debug` version of `erizo.js` with its source map now. 
=> Enable sourcemap for bundle

erizo_controller/common/amqper.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/roomController.js
Improvements to external input functionality.
**8da578b log specific error on external input error**
Output the specific error when adding external input fails.
**9ea7fe4 add optional custom timeout for callRpc**
add optional Timeout param to `callRpc` function.
**2ceb3d5 increase timeout for ExternalInput callRpc call**
Start to consume a RTSP source could take more than the default 5000 timeout so this commit increase the wait to complete to 20000 for adding an external input call.
Changes in Server public API, see 9ea7fe4.
[NO] It includes documentation for these changes in `/doc`.
=> External input improvements

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Socket.js, erizo_controller/erizoController/erizoController.js
Messages could be sent even if the Room was not connected yet. 
Also `socket.disconnect` no longer existed.
=> Avoid sending messages when socket is not connected

scripts/installMacDeps.sh, scripts/installUbuntuDeps.sh, scripts/travisInstallDeps.sh
Disable docs in libav installation. Was problematic in Mac and removed them from the others as we don't really need them 
=> Disable docs in libav configure

doc/client_api.md, erizo_controller/erizoClient/src/ErizoFc.js
This PR adds exporting the Logger in ErizoFc and fixes the docs for it as they were outdated since we refactored ErizoClient.
Fixes #996 
=> Added logger to ErizoFC

erizo_controller/erizoClient/src/Room.js, spine/simpleNativeConnection.js
This PR fixes two problems:
1. Spine was not properly creating Streams for publication - this PR updates it to use the new API
2. `hasAudio()` and `hasVideo()` were returning the full `video` or `audio` entries of the configuration.  When creating the Connection `getErizoConnectionOpts` was passing in the subscribing side, where we only need `true` or `false`
=> Fixed spine publishing and publishing and subscribing in the same process

erizo_controller/erizoClient/gulpfile.js, erizo_controller/installErizo_controller.sh, spine/installSpine.sh
We were repeating work when installing licode as the gulp default task builds both `erizofc` and `erizo`. This PR adds a new task per target in gulp for `ErizoClient`. The installation scripts are also updated to use these tasks.
=> Added a gulp task per target

erizo/src/erizo/WebRtcConnection.cpp
The `IncomingStatsHandler` was positioned in a way that all feedback RTCP traffic in a subscriber was already filtered (in simulcast). We're losing all the RTCP information in that case. 
By moving it below the `QualityFilterHandler` we get that information... There are, however other problems since we've already filtered out all the NACKs that we've successfully recovered in the `RtpRetransmissionHandler`. 
We probably need to rethink this but this is the minimal change that will get us some RTCP stats to display.
Please note that most of the stats gathered by both the `StatsHandlers` are purely informative except `totalCalculatedBitrate` which is not affected by this PR.
[] It includes …
=> Move IncomingStatsHandler to parse Incoming RTCP packets from subscriber

.gitignore, spine/runSpineClients.js, test/.eslintrc.json, test/licode_default.js, test/package.json, test/perf-tests.js, test/rtp_media_config_default.js, test/runSpineTest.sh, test/utils/remote-spine.js
Add the option to run performance tests in the future. It's focused to run Licode and Spine clients on Amazon EC2 instances.
This is still in progress, so please do not merge it.
Not needed?
=> Add scripts to run performance tests

.circleci/config.yml, erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/rtp/PliPacerHandler.cpp, erizo/src/erizo/rtp/PliPacerHandler.h, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h, erizo/src/erizo/thread/Worker.cpp, erizo/src/erizo/thread/Worker.h
Fixes a leak in the array of cancelled scheduled tasks. Actually it gets rid of such list and uses shared_ptrs instead.
Not needed.
=> Fix a leak when cancelling scheduled tasks

extras/docker/initDockerLicode.sh, spine/log4cxx.properties, spine/runSpineClients.js, spine/simpleNativeConnection.js, test/licode_default.js, test/package.json, test/perf-tests.js, test/runSpineTest.sh, test/utils/remote-spine.js
This adds the first stress tests. And I continued refactoring the scripts somehow to improve test readability.
Not needed.
=> Added first stress tests and improve test scripts

erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/LayerDetectorHandler.h
LayerDetectorHandler now reads frame width, height and rate for each Spatial and Temporal layer (VP9 and VP8). In another PR I will send this information to each subscriber to let them decide which layer they'll filter based on client's capabilities.
Not needed.
=> LayerDetectorHandler reads also resolution and framerate

.circleci/config.yml, Dockerfile, erizo/buildProject.sh, erizo/cleanObjectFiles.sh, erizo/generateProject.sh, erizo/src/erizo/CMakeLists.txt, erizo/src/erizo/SrtpChannel.cpp, erizo/src/erizo/media/ExternalInput.cpp, erizo/src/erizo/media/MediaProcessor.cpp, erizo/src/erizo/media/codecs/AudioCodec.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/RtcpAggregator.cpp, erizoAPI/binding.gyp, erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/erizoAgent/launch.sh, erizo_controller/erizoJS/erizoJS.js, erizo_controller/initErizo_agent.sh, extras/basic_example/basicServer.js, extras/basic_example/public/script.js, extras/docker/initDockerLicode.sh, scripts/initLicode.sh, scripts/installErizo.sh
This PR adds "Release" and "Debug" configurations for both erizo and erizoAPI. The main difference is that Erizo is now built with `-O3`. Both are built by default, while "Release" is the one that's normally used by ErizoJS.
In order to run the debug version of both erizo and erizoAPI, you can start erizoAgent with `initErizoAgent.sh -d` or, if you are running the docker image, you can add `--erizoDebug`.
Also, we're now using `rpath` when building erizoAPI, meaning that we no longer need `LD_LIBRARY_PATH` for Licode.
**Warning for Spine users**: You do need `LD_LIBRARY_PATH` and note that `liberizo` is now under `erizo/build/release/erizo` or `erizo/build/debug/erizo` .
Finally, in the Docker image we're keeping both builds but removing the object files in `CMakeFiles`to …
=> Add options to erizo build process

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizo/src/erizo/media/MediaProcessor.cpp, erizo/src/erizo/media/MediaProcessor.h, erizo/src/erizo/media/OneToManyTranscoder.cpp, erizo/src/erizo/media/OneToManyTranscoder.h, erizo/src/erizo/pipeline/Handler.h, erizo/src/erizo/pipeline/HandlerContext-inl.h, erizo/src/erizo/pipeline/Pipeline.cpp, erizo/src/erizo/pipeline/Pipeline.h, erizo/src/erizo/pipeline/Service.h, erizo/src/erizo/pipeline/ServiceContext-inl.h, erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/LayerDetectorHandler.h, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/test/OneToManyProcessorTest.cpp, erizo/src/test/utils/Mocks.h, erizoAPI/ExternalInput.cc, erizoAPI/SyntheticInput.cc, erizoAPI/WebRtcConnection.cc
Adds a way to send async events from pub to subs. That way we can safely notify about different events and they will be synced with the media data.
Not needed.
=> Send async events from pub to subs

erizo_controller/erizoJS/erizoJS.js
We were loading both versions of liberizo (debug and release) in some cases, which caused some unexpected behaviour.
Not needed.
=> Fix usage of liberizo debug version from ErizoJS

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoJS/models/Publisher.js
It enables the option to mute audio or video before publishing or subscribing a stream. This could fix race conditions when we want to automatically mute a stream we're receiving.
No new API, but we now can do something like the example below:
```js
room.addEventListener('stream-added', function (streamEvent) {
const stream = streamEvent.stream;
stream.muteAudio(true);
room.subscribe(stream);
});
```
=> Add the option to mute audio/video before publishing/subscribing

erizo_controller/erizoAgent/erizoAgent.js, scripts/licode_default.js, test/licode_default.js
Added the option to load the debug ErizoAPI addon in the ErizoAgent section of `licode_config`
=> Add erizoJS debug option in configuration

doc/client_api.md, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js
It adds a new API to configure the max width/height/frameRate we want to receive in a subscribed video. It could be really useful in Simulcast, when to make sure we won't receive a video larger than the size of the <video> element, or if we want to stop wasting bandwidth/CPU in the client side.
When we enable Simulcast it is also interesting to specify whether the subscriber should not receive a resolution or frame rate beyond a maximum. We
can configure it like in the example below:
```js
room.subscribe(stream, {video: {height: {max: 480}, width: {max: 640}, frameRate: {max:20}}}, function(result, error){
if (result === undefined){
console.log("Error subscribing to stream", error);
} else { …
```
=> Add an API to limit the max subscribed video resolution and framerate

erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/test/rtp/QualityManagerTest.cpp
Add logic into QualityManager to decide the best layer based on client's constraints too.
=> Make QualityManager decide the best layer upon constraints

erizo_controller/erizoJS/models/Publisher.js
Fixes a bug that was converting 0 values to -1 on constraints received in erizoJS.
Not needed.
=> Accept zero as a value in video constraints.

erizo_controller/common/amqper.js, erizo_controller/common/logger.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Socket.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Channel.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/models/Room.js, erizo_controller/erizoController/models/Stream.js, erizo_controller/erizoController/nuveProxy.js, erizo_controller/installErizo_controller.sh, erizo_controller/test/erizoController/erizoController.js, erizo_controller/test/utils.js
Some code refactoring in Erizo Controller. Now we use the next models to improve code readability: 
* Stream: this one is not new, represents a published stream. 
* Channel: a basic transport channel that checks received tokens.
* Client: represents an end client connection. Stores its room, streams, etc. Handles events received from the client side.
* Room: represents a room, with clients and streams.
Not needed. All changes are in the backend.
=> Erizo Controller refactoring to add Clients and Channels

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/WebRtcConnection.cpp, erizo_controller/erizoClient/src/Socket.js
Fix some occasional Erizo crashes that happen when closing resources.  It also fixes an minor issue in Erizo Client.
Not needed.
=> Fix some Erizo crashes

erizo/src/erizo/SdpInfo.cpp
Fix fmtp parsing in SDPInfo. With this change we'll be able to finally use h.264 with multiple browsers (Firefox and Chrome). We'll have to configure `rtp_media_config.js` with something like:
```js
mediaConfig.rtpMappings.h264 = {
payloadType: 101,
encodingName: 'H264',
clockRate: 90000,
channels: 1,
mediaType: 'video',
formatParameters: {
'profile-level-id': '42e01f',
'level-asymmetry-allowed': '1',
'packetization-mode': '1',
},
feedbackTypes: [
'ccm fir',
'nack',
'nack pli',
'goog-remb',
],
};
```
Not needed.
=> Fix fmtp parsing in SDPInfo to use h.264 profiles

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h
Bring ExternalOutput code up to date by applying our coding style:
- CamelCase -> snake_case_
- NULL -> nullptr
- this-> -> 
- CAPITAL_CONSTANT -> kConstant
- Member initializer list with brackets
- member_variable -> member_variable_ 
Not needed.
=> Apply coding style to ExternalOutput

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizoAPI/ExternalOutput.cc, erizo_controller/erizoJS/models/Publisher.js, spine/nativeClient.js
ExternalOutput will now depend on the values set on `rtp_media_config.js` , so that it will be more dynamic and less prone to errors due to wrong configurations.
Not needed.
=> Pass media config to ExternalOutput and make video configuration dynamic

doc/server_api.md, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/erizoController/erizoController.js, erizo_controller/test/erizoController/roomController.js, erizo_controller/test/erizoJS/erizoJSController.js, extras/basic_example/basicServer.js, extras/basic_example/public/script.js, nuve/nuveAPI/resource/roomResource.js, nuve/nuveAPI/resource/roomsResource.js, nuve/nuveAPI/resource/tokensResource.js, scripts/rtp_media_config_default.js
This PR adds support to configure codecs per room, instead of having the same codec configuration for all rooms in a Licode instance. The list of available configurations will be setup in the `rtp_media_config.js` file, and we can add/remove the proposed configurations in `rtp_media_config_default.js`.
The proposed configurations are:
```js
mediaConfig.codecConfigurations = {
default: { rtpMappings: { vp8, opus }, extMappings },
VP8_AND_OPUS: { rtpMappings: { vp8, opus }, extMappings },
VP9_AND_OPUS: { rtpMappings: { vp9, opus }, extMappings },
H264_AND_OPUS: { rtpMappings: { h264, opus }, extMappings },
};
```
But we could also add other examples like:
```js
VP8_AND_PCMU: { rtpMappings: { vp8, pcmu }, extMappings },
```
Now we …
=> Add support to configure codecs per room

erizo_controller/erizoClient/src/utils/L.Resizer.js, erizo_controller/erizoClient/src/views/AudioPlayer.js, erizo_controller/erizoClient/src/views/VideoPlayer.js
Fixes #1021 . Wrong CSS rules initialization in Erizo Client Resizer. Thanks @HemanthAnakapalle for the heads up.
It also adds two small changes to get rid of some warning on client side.
Not needed.
=> Fix Erizo Client Resizer and use stream.srcObject

erizo/src/erizo/SdpInfo.cpp, erizo/src/test/assets/Chrome.sdp, extras/docker/initDockerLicode.sh
There was an issue parsing the SDP issued by old versions of Chrome.
Not needed.
=> Fix Erizo SDP parser

erizo_controller/erizoController/erizoController.js, scripts/licode_default.js
ErizoControllers send keep alive messages to Nuve as a health check. If Nuve receives a message from an unknown (not previously identified) ErizoController, it will answer the keep alive message with `whoareyou`. 
This PR allows to modify the behavior of ErizoController when receiving this message by configuration. If `exitOnNuveCheckFail` is enabled, ErizoController will automatically exit.
=> Add close ErizoController on KeepAlive failure

erizo/src/erizo/pipeline/Pipeline-inl.h, erizo/src/erizo/pipeline/Pipeline.cpp, erizo/src/erizo/thread/Scheduler.cpp
We've seen some crashes in Erizo that does not show info such as a backtrace, and it seems like it can be cause by an error thrown that is not properly [handled by GCC probably](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55917).
Not needed.
=> Remove usage of "throw errors" in Erizo

erizo_controller/erizoClient/src/Connection.js
This PR fixes screen sharing streams initialization when no video parameter is included.
=> Fixed screen sharing when no video param is included in config

erizo/src/erizo/SdpInfo.cpp, erizo_controller/common/semanticSdp/MediaInfo.js, erizo_controller/common/semanticSdp/SDPInfo.js
There is something wrong in the current SDP parser that is affecting Simulcast and some feedback mechanisms. I've compared the SDPs generated by the previous solution and the current one and this is the only thing that is different, and that could be causing those issues. Not sure 100% if there is any other cause.
There was another issue caused by sending a=ssrc and a=ssrc-group in a different order compared with the previous SDPs. SdpInfo.cpp is not perfect and expected to receive a=ssrc-group first, which is not happening now. I added a temporal fix given that we'll eventually get rid of SdpInfo.cpp with the new parser.
Not needed.
=> Update the media port in the SDP parser

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js
For v5 we'll still send SDPs as strings instead of format them in JSON objects. 
Not needed.
=> Use strings to send the SDP within signalling messages.

erizo/src/erizo/rtp/RtcpNackGenerator.cpp, erizo/src/test/rtp/RtcpNackGeneratorTest.cpp
I run into this bug while looking at the nack generator (related to pr #1096 ). Something was off in the sequence of nacks generated and then I found that the first nack of the second blp was always missing.
[X] It needs and includes Unit Tests
The for inside the test case works but maybe the form can be improved
=> Fix missing generated nack

erizo_controller/common/semanticSdp/MediaInfo.js, erizo_controller/common/semanticSdp/SDPInfo.js, erizo_controller/common/semanticSdp/SimulcastInfo.js
Implemented a proper parser for the old implementation of Simulcast (such the one in Firefox).
Simulcast on Firefox was working only thanks to a coincidence.
Fix simulcast not working on https://github.com/lynckia/licode/pull/1098
=> Firefox Simulcast parser

utils/release.sh
We were having issues when creating a release. The issue was affected by commit with names that contain double quotes.
Not needed.
=> Remove double quotes in the release description

nuve/nuveAPI/mdb/tokenRegistry.js, nuve/nuveAPI/resource/tokensResource.js
Handle Nuve addToken error to prevent crash
=> Handle Nuve addToken error

erizo/src/erizo/media/ExternalOutput.cpp
- Fixed recordings could not be generated before stopping recording.
=> Need to set video time base before pushing packets.

erizo_controller/erizoController/models/Client.js
Sometimes happens that targetClient is undefined and the whole thing crashes because can't find sendMessage of undefined;
=> check if targetClient is undefined

erizo/src/erizo/NicerConnection.cpp, erizo/src/erizo/NicerConnection.h
We found a bunch of issues in NicerConnection that could be caused by a wrong smart pointer handling in NicerConnection::async function.
Not needed.
=> Fix async function in NicerConnection

utils/release.sh
Fix wrong log parsing when creating releases.
Not needed.
=> Fix wrong log parsing when creating releases

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/IceConnection.cpp, erizo/src/erizo/IceConnection.h, erizo/src/erizo/LibNiceConnection.cpp, erizo/src/erizo/LibNiceConnection.h, erizo/src/erizo/NicerConnection.cpp, erizo/src/erizo/NicerConnection.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/test/LibNiceConnectionTest.cpp, erizo/src/test/NicerConnectionTest.cpp
There's still some cases where NicerConnection makes Erizo crash when closing a connection. This PR aims to solve them by destroying things in the correct threads.
Not needed.
=> Fix a crash that still happens when closing NicerConnection

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h
- Because the return value of `av_guess_format()` is a pointer to a
global object, we can not use it to save the codec type for each
`ExternalOutput`.
=> Use private variables to save the codec type of the output format.

erizo/src/test/media/SyntheticInputTest.cpp, erizo/src/test/rtp/SenderBandwidthEstimationTest.cpp
We have been having few annoying failures on unit tests that break our CI process. I made two tweaks to constant values and it works much better for us, now we got 100% build success in several thousands test runs.
=> Fix random unit test failure

erizo/src/erizo/media/Depacketizer.cpp, erizo/src/erizo/media/Depacketizer.h, erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/test/media/DepacketizerTest.cpp
This PR integrates the new `Depacketizer` into `ExternalOutput` replacing all the old vp8 depacketizer login. As part of the process of integrating it, this PR updates the `Depacketizer` to better suit the rest of Erizo naming conventions and removing the `throw` code.  
This PR also adds support for H264 in recording new that we have a compatible depacketizer, that required a minor change in `LayerDetectorHandler` to start marking the spatial layer of h264 packets (for now it's always 0).
=> Integrate depacketizer in ExternalOuput adding h264

erizo_controller/erizoClient/src/utils/SdpHelpers.js
This fixes audio bitrate when we limit the max audio bandwidth in the pub/sub options.
Not needed.
=> Fix wrong max audio bandwidth setting

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h
We were having ICE fail connections after having been successfully established. The issue was that we were setting again ICE credentials when Erizo received a new SDP, and the underlying ICE library set that status to fail.
=> Fix calls to updateSpec function that caused failing ICE connections

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizo/src/erizo/pipeline/HandlerManager.h, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizoAPI/ExternalOutput.cc, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/erizoJS/erizoJSController.js
It adds a new worker + pipeline to ExternalOutput, so that we can handle simulcast layers and filter them. Now we record the higher available layer, but we might want to create an API in the future to record the lower or any intermediate layers instead.
Not needed.
=> Add full simulcast support to recordings

erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizoAPI/ConnectionDescription.cc, erizoAPI/ConnectionDescription.h, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Helpers.js, erizo_controller/erizoJS/models/SessionDescription.js, erizo_controller/test/utils.js, spine/nativeClient.js
It moves the logic to create SDP offer from Erizo to ErizoJS.
Not needed.
=> Move offer creation logic out of Erizo

erizo/src/erizo/NicerConnection.h, erizo/src/erizo/media/ExternalInput.h, erizo/src/erizo/rtp/RtcpRrGenerator.h, erizo/src/erizo/stats/StatNode.h, erizo/src/test/NicerConnectionTest.cpp
This PR addresses the few build errors that precluded licode's compilation on gcc 7 and clang 3.9 (linux)
=> Make licode work on gcc 7 and clang 3.9

nuve/nuveAPI/resource/tokensResource.js
I think we need to set a default mediaConfiguration in case is not passed when creating token
=> set a default mediaConfiguration to avoid addon crash

erizo_controller/erizoClient/src/Connection.js
We were not using the selected window/screen in Electron apps.
Not needed.
=> Fix screensharing when loading ErizoClient in an Electron App

erizo_controller/erizoClient/src/utils/L.Resizer.js
Should fix https://github.com/lynckia/licode/issues/1154
=> Fix a JS error thrown by a wrong DOM access within the Resizer

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h
This PR adds initial support for handling multiple streams in a single WebRtcConnection inside Erizo.
Not needed.
=> Initial support for multiple MediaStreams in a single WebRtcConnection

erizo_controller/erizoJS/adapt_schemes/notify-slideshow.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Node.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/erizoJS/erizoJSController.js
This PR refactors the way we handle messages in ErizoJSController. The main idea is to decouple things between ErizoJSController, Connection, Publisher and Subscriber, while keeping the focus on making things easier for Single Peer Connection.
Not needed.
=>  Decouple Connection logic in ErizoJS

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Socket.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Channel.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/models/Room.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/test/erizoController/erizoController.js, extras/basic_example/public/script.js, scripts/licode_default.js
A new option has been added to enable Single PC when publishing/subscribing to Erizo. It also forwards this flag to ErizoJS, which is also responsible for reusing existing Connections when it's enabled.
It needs documentation, but I haven't added it yet since it's still experimental (it's actually broken right now) and we don't want people to start playing with it. 
=> Add a new API to enable Single PC in ErizoClient

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/test/utils/Mocks.h, erizoAPI/MediaStream.cc, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoController/models/Channel.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/erizoJS/erizoJSController.js, scripts/installErizo.sh, spine/Events.js, spine/nativeClient.js
This Pull Request is a set of changes to fix a bunch of issues that I found during the initial implementation of Single Peer Connection. Probably not all issues will be resolved in this first round, but at least it should lead us to something more or less reliable to start experimenting with it broadly. 
Since this PR is getting bigger and bigger I will try to fix issues in individual commits to make reviewers work a bit easier. At some point, if it's too big I will merge this PR and create another with more fixes.
*Note*: These things needed to make Single PC work properly will not be part of this PR:
- Detect compound RTCP packets and forward each part to the corresponding MediaStream.
- Get rid of the fixed 55543 and 44444 ports and make them unique for each stream.
- …
=> Fix several crashes and bugs in Single Peer Connection

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/RtcpAggregator.cpp, erizo/src/erizo/rtp/RtcpForwarder.cpp, erizo/src/erizo/rtp/RtpHeaders.h, erizo/src/erizo/rtp/RtpPaddingRemovalHandler.cpp, erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp, erizo/src/erizo/rtp/RtpSlideShowHandler.cpp, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h, erizo/src/test/utils/Tools.h
RTCP was not being forwarded to the right MediaStreams for two reasons: there are compound RTCP packets that we didn't take into account, and there are also REMB packets that handle the SSRC info in a different way.
=> Fix RTCP forwarding in Single PC

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h, erizo/src/test/WebRtcConnectionTest.cpp, erizo/src/test/utils/Mocks.h
Adds support to forward REMB packets to each stream referenced in the list, and update the bitrate with the corresponding value.
Not needed.
=> Improve support to forward REMB packets to each stream

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/utils/SdpHelpers.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/erizoJS/erizoJSController.js, erizo_controller/test/utils.js
Add maxVideoBW as a config instead of part of SDP when using Erizo. This allows us to set different limits for each Stream when using Single Peer Connection.
It also includes some fixes. For instance, Firefox was not working anymore, and updateConfiguration/muteStream could fail in some cases.
Not needed.
=>  Add maxVideoBW as a config instead of part of SDP when using Erizo

erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h
Fix some crashes that seem to happen when calling uv_close(). My guess is that it then asynchronously calls uv_finish_close with an object (uv_handle_t) which is already destroyed, so the memory is corrupted.
=> Fix crashes calling uv_finish_close

doc/client_api.md, scripts/licode_default.js
The role of maxVideoBW for subscribed streams was not clear in the docs. This PR updates that and fixes some typos.
=> Updated docs to clarify maxVideoBW and defaultVideoBW

erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/erizoAgent/erizoList.js, erizo_controller/test/erizoAgent/erizoList.js
Refactoring ErizoAgent to better handling ErizoJSs and processes. It manages a single list with ErizoKS (idle or not) and their processes.
Not needed.
=> Refactor ErizoAgent with a new list of ErizoJS

erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/erizoAgent/erizoList.js, erizo_controller/erizoController/ch_policies/default_policy.js, erizo_controller/erizoController/ecCloudHandler.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/roomController.js, erizo_controller/test/erizoAgent/erizoAgent.js, erizo_controller/test/erizoController/ecCloudHandler.js, erizo_controller/test/erizoController/roomController.js, scripts/licode_default.js
Add an option in the config file to set a limit of Erizos per room. 
Not needed.
=> Add option to set limit of Erizos per Room

erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
Uses new promise-based API to fix simulcast in Firefox
Not needed
=> Uses new promise-based API to fix simulcast in Firefox

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
By WebRTC spec, RTCIceCandidate.candidate is a readonly attribute. It makes
more sense to store, check, and concatenate candidate attribute line in another
variable, instead of the event object.
Spec: https://www.w3.org/TR/webrtc/#dom-rtcicecandidate
macOS Safari implements the event behavior by the spec. Include this patch to make Safari work correctly.
=> Use a variable instead of event object to concatenate candidate attr.

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js
Seems that with the single pc refactor something went lost.
oniceconnectionstatechange was not propagated successfully so no one was receiving the failed state
=> Fix the way ICE propagates connection state events

extras/basic_example/basicServer.js
isNaN('inputRoomName') returns true. Given a string of specific room name,
original implementation never assigns the specific room name to the
variable, resulting in generating new token of default room.
Remove the isNaN() call and simply check if the input value is truthy just
like what we do on other parameters.
=> Do not check if room param is NaN in basic example server.

erizo_controller/erizoJS/erizoJSController.js
In high concurrency, call connection.addRemoteCandidate may crash(because connection has close) in function that.processSignaling
=> Fix crashes in addRemoteCandidate when subscriber is not removed from publisher

erizo/src/erizo/MediaStream.cpp
**Made pipeline usage in erizo::MediaStream more safe**
Using shared pointer (pipeline_) directly after std::shared_ptr::reset() (in erizo::MediaStream::syncClose()) may be unsafe. A simple check before dereferencing it makes the task execution safe even after syncClose task.
=> Added pipeline_ shared_ptr check before dereferencing it.

erizo_controller/erizoClient/src/Room.js
ATM we are assigning the room only when the stream is added after the room connect (socketOnAddStream).
this will also assign the room to the stream object when connecting to the room
=> Room is not assigned to remote streams when receiving stream list in room connect evt

erizo/src/erizo/DtlsTransport.cpp, erizo/src/erizo/DtlsTransport.h, erizo/src/erizo/IceConnection.cpp, erizo/src/erizo/IceConnection.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/dtls/DtlsClient.cpp, erizo/src/erizo/dtls/DtlsSocket.h, erizo/src/erizo/logger.h, erizo/src/erizo/media/ExternalOutput.cpp
**PARTIAL CODE REVIEW**
Basically the main change is adding Handlers to the pipeline as "make_shared" pointer.
=> Small code review like avoiding redundant objects copy.

erizo_controller/erizoJS/erizoJSController.js
after wrtc.close(), need update publishers immediately
=> unsafe under high concurrency

erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h, erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizoAPI/ConnectionDescription.cc, erizoAPI/ConnectionDescription.h, erizo_controller/erizoJS/models/SessionDescription.js
There are new experimental features in Chrome that enable Simulcast for Screensharing and h.264 Streams. This PR fix some issues I found in the first tests I run.
Not needed.
=> Add support to Screensharing and h264 simulcast

.circleci/config.yml, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/erizoController/erizoController.js, erizo_controller/test/erizoController/roomController.js
There was some issues in Single Peer Connection when trying to unsubscribe or unpublish streams because we were not negotiating the SDP again. This PR adds such negotiation and it also introduces some minor fixes.
Not needed.
=> Fix unpublish and unsubscribe for Single PC

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h
Use fixed values for bw estimation in Single PC when the stream is in slideshow mode.
Not needed.
=> Use fixed values for bw estimation when slideshow is enabled

erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp
This PRs rolls back a temporary fix for Firefox clients which is already fixed in this browser. It seems to be affecting our production environment in some cases.
Not needed.
=> Enable last padding packet again to avoid sticky bitrates

erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp
This PR prevents `BandwidthEstimationHandler ` from reading packets or processing data if it hasn't been initialized before.
=> Check if the handler is initialized before reading or processing

erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Stream.js
When closing a stream we are currently NOT unbinding from this:
https://github.com/lynckia/licode/blob/18c5562a312b080468f6fdc5f8a0ccec1abbcf54/erizo_controller/erizoClient/src/Room.js#L126
Steps to reproduce:
tab 1) Publisher 
tab 2) subscriber. Subscribe to remote stream, then unsubscribe, then subscribe again. 2 stream added events are fired
[] It needs and includes Unit Testsì
=> When closing streams, also unbind from all events.

erizo_controller/erizoClient/src/Room.js
When setting a maxVideoBw in p2p subscriber mode, this is ignored.
This is because the stream is populated at the first offer received from the other side.
=> Fix maxVideoBw on p2p subscriber

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/test/log4cxx.properties, erizo_controller/erizoAgent/log4cxx.properties
This PR adds the option to print periodic stats every 30 seconds into the logs. The stats follow this format:
```bash
[erizo-150ad5ee-6c6e-1941-bf9b-839c2e7e9739] 2018-07-27 10:05:24,473  - INFO [0x70000a9c8000] StreamStats - {"SL0TL0":0,"SL0TL1":0,"SL0TL2":0,"SL0TL3":0,"SL1TL0":0,"SL1TL1":0,"SL1TL2":0,"SL1TL3":0,"SL2TL0":0,"SL2TL1":0,"SL2TL2":0,"SL2TL3":0,"SL3TL0":0,"SL3TL1":0,"SL3TL2":0,"SL3TL3":0,"audioBitrate":40359,"audioFL":0,"audioJitter":0,"audioMuted":0,"audioPL":0,"bwe":0,"isPublisher":1,"maxActiveSL":0,"maxActiveTL":0,"metadata":{"type":"publisher"},"paddingBitrate":0,"selectedSL":0,"selectedTL":0,"totalBitrate":523814,"videoBitrate":162561,"videoFL":0,"videoJitter":0,"videoMuted":0,"videoPL":0}
```
**Changes in Client or …
=> New option to print periodic stats as logs

erizo/src/erizo/rtp/QualityManager.cpp
We were not disabling padding in some cases where layers where capped by API.
Not needed.
=> Disable padding on capped bitrates

erizo/src/erizo/rtp/RtpVP9Parser.cpp
I've post an issue [#1269](https://github.com/lynckia/licode/issues/1269) disscuss “add vp9 support”. In my tests, RtpVP9Parser.cpp vp9 payload len is not correct, it should - vp9 headers lens. This is only a small modification part in my "MIXER" version. I'm going to do what I can  to add vp9 support.
=> RtpVP9Parser vp9 payload len

erizo_controller/erizoClient/src/Stream.js
In screen sharing (spec.screen == true), video may be passed as null. When it's null and video size is defined, a null reference exception occurs.
This PR should solve issue #1253 .
No change
=> Fix for mishandling of videoOpt in Stream.js

erizo/src/test/LibNiceConnectionTest.cpp, erizo/src/test/NicerConnectionTest.cpp
**Bug is related to NicerConnectionTest and LibNiceConnectionTest**
It was found out in the CI of the PR https://github.com/lynckia/licode/pull/1287
Basically the problem was in calculating the memory used by a string using sizeof().
It works only with memory allocation to stack like "char var[DEFAULT_SIZE];", in this case sizeof(var) == DEFAULT_SIZE.
With dynamic memory allocation like "char* var = new char[DEFAULT_SIZE];" or "char* var = (char*)malloc(DEFAULT_SIZE);" the sizeof(var) == sizeof(void*) and it can be bigger then the actual memory allocated leading to a bad memory access.
=> Fix some random bugs in cpp tests

erizo/src/erizo/MediaStream.cpp
By looking at stats it's usually hard to understand if bitrate is low due to network issues or some constraint given by settings, so I added maxVideoBW to the stats.
Not needed.
=> Add maxVideoBW to stats

erizo_controller/erizoJS/models/Subscriber.js
We were receiving events in a closed Subscriber because we don't remove the listener.
Not needed.
=> Stop receiving MediaStream events when subscriber is closed

erizo/src/erizo/MediaStream.cpp
`media_stream_event_listener_` was not being initialized. That could cause crashes, specially running the slideshowbeloylayer tests in some environments.
=> Initialize event listener to nullptr

Dockerfile, doc/from_source.md, scripts/installUbuntuDeps.sh
This PR fixes a compatibility issue with Ubuntu 16.04 and sets it as the default for the docker builds.
Once this PR is merged, all our tests will be run with the new docker image so Ubuntu 16.04 will be our supported Ubuntu version - this PR also updates the docs accordingly
[X] It includes documentation for these changes in `/doc`.
=> Update to Ubuntu 16.04

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/erizo/rtp/RtpSlideShowHandler.cpp, erizo/src/test/rtp/QualityManagerTest.cpp, erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js
This PR updates #1199, adding the possibility to enable SlideShow when below layer 0, effectively replacing Fallback mode if desired.
This is useful, for example, when activating simulcast with Screen sharing. Instead of getting a frozen frame, users with low bandwidth will get an updated image (of the lowest possible quality) every few seconds.
Additionally, this PR updates the API to better reflect this behaviour and cleans up some of the variable names.
=> API to enable slideshow keyframes below a spatial layer

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/thread/Worker.cpp, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoJS/erizoJSController.js
We weren't removing singlePC that was previously closed in ErizoClient. I also added some other minor fixes I found while debugging this issue.
Not needed.
=>  Remove closed singlePC connection in ErizoClient

erizo/src/erizo/MediaStream.cpp, erizoAPI/WebRtcConnection.cc
This fixes potential  concurrency problems when managing `SdpInfo` in `ConnectionDescription` `WebRtcConnection` and `MediaStream`, they all shared the same pointer causing problems. They don't need a shared pointer and the info can be copied when needed, at very specific points.
=> copy sdpInfo when passed to and from WebRtcConnection

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/bandwidth/TargetVideoBWDistributor.cpp, erizo/src/erizo/rtp/StatsHandler.cpp, erizo/src/test/bandwidth/TargetVideoBWDistributor.cpp, erizo/src/test/utils/Mocks.h
There was a race condition when accessing bitrate stats from WebRtcConnection's worker. So I implemented this solution to update the stat whenever it changed by using an atomic variable.
Not needed.
=> Fix concurrency issues in video bitrate stats access

erizo/src/erizo/rtp/QualityManager.cpp
This PR fixes a crash that could potentially happen when calling `enableSlideShowBelowSpatialLayer` before `QualityManager` is initialized
=> Fixed crash when enablingSlideShowBelowSpatialLayer when un initialized

erizo/src/erizo/WebRtcConnection.cpp, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js, extras/basic_example/public/script.js
There was an issue in Single Peer Connection by which we were not negotiating SDP properly when the first subscribed stream had only audio.
Not needed.
=> Fix SDP negotiation when a stream is audio only

erizo/src/erizo/thread/Worker.cpp
Fix wrong skew correction in the scheduler
Not needed.
=> Fix wrong clock skew correction in the scheduler

erizo_controller/erizoController/models/Room.js
Fixes crash introduced in eslint PR. e
=> Use forEach in the Map instead of Map.values()

erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h
This PR makes the burst size for the Token Bucket used in `PaddingGeneratorHandler` variable.
Before this PR, the burst size was a constant but we are trying to send a variable amount of packets depending on the target padding bitrate. It makes sense to also make variable the burst size that the tokenBucket will allow.
The maximum and minimum burst sizes are bounded to avoid bursts that are too big and, at the same time, avoid setting a burst limit too small.
=> Burst size is now calculated depending on the packets to be sent

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/rtp/QualityManager.cpp
Add info to log whether a stream quality is capped by layer constraints
Not needed.
=> Add info to log whether a stream quality is capped by layer constraints

erizo/src/erizo/dtls/DtlsClient.cpp, erizoAPI/addon.cc
The ssl init and the creation of the static certificate used in the session where being created in the `DtlsSocketContext` constructor and the `Init` static function was not thread-safe. 
This PR avoids this problem by initializing those fields in the initialization of the  Node Addon which is done synchronously when starting the ErizoJS process
=> Do SSL/DTLS init on addon start instead of in DtlsClient constructor

erizo_controller/erizoController/models/ErizoList.js
This PR solves a race condition when rapidly publishing multiple streams on the first use of the same ErizoJS process. We were subscribing to the event for a different position in the list.
=> Fix events on erizoList

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/FakeKeyframeGeneratorHandler.cpp, erizo/src/erizo/rtp/FakeKeyframeGeneratorHandler.h, erizo/src/test/log4cxx.properties, erizo/src/test/utils/Mocks.h
This PR improves `FakeKeyframeGeneratorHandler` by making sure it's only active (transforming packets and requesting new keyframes) when the transport that will receive the packet is ready.
=> FakeKeyframeGeneratorHandler only acts if transport is ready

nuve/nuveAPI/mdb/roomRegistry.js
The es6 and eslint compliant version of the db.eval call causes problems with older versions of mongodb. This PR reverts the changes and disables linting in that area.
=> Go back to pre-es6 version of the db.eval function

erizo/src/third_party/nicer.cmake
There was a memory corruption in latest nicer so we need to update it.  More info here: https://github.com/lynckia/nrappkit/pull/3
Not needed.
=> Fix memory corruption with latest nicer

erizo_controller/common/amqper.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/models/Publisher.js
This PR mainly fixes an issue when unsubscribing multiple streams at the same time. But it also adds more logging in RoomController and fixes a memory leak when using amqper.
Not needed.
=> Fix issues when unsubscribing streams

doc/client_api.md, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/models/Connection.js
This PR adds a new event called `stream-unsubscribed` for some special cases where we want to exactly know when the stream no longer lives in client or server side.
Yes, it adds a new event `stream-unsubscribed`. See doc/client_api.md for further info.
=> Add a new stream-unsubscribed event

erizo_controller/common/amqper.js
There were periodic errors when `callRpc` was called without a callback.
This PR fixes this by properly setting a default callback
=> Properly set default callback in callRpc

extras/basic_example/public/index.html, extras/basic_example/public/script.js
Using Chrome in some environments, the `onlySubscribe` option for basic_example would only show the spinning logo instead of playing the video streams.
This issue is caused by the [autoplay policy update](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).
This PR updates basic_example to force a click in a new `start` button only when `onlySubscribe` is enabled. This check can be bypassed by using the `noStart` parameter. This can be useful when you know `MEI` for you is high enough in a given domain.
=> Add start button in basicExample for onlySubscribe

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/SessionDescription.js
This PR fixes potential issues when handling multiple simultaneous negotiations in singlePC.
- Offer SDP queue is now properly ordered
- Offer SDPs generated in Erizo now update `sessionVersion` properly
- When processing unsubscriptions, streams are now not removed directly in the SDP. It is generated again
=> Fix negotiation problems in Single PeerConnection

erizo_controller/erizoJS/models/Connection.js
ResendLastAnswer can be called after closing the connection. `wrtc` is not available anymore so it results in a ErizoJS crash
=> Fix crash in resendLastAnswer

erizo/src/erizo/stats/StatNode.cpp, erizo/src/test/stats/MovingIntervalRateStatTest.cpp
There is an exception that happens from time to time in Erizo due to a bad calculation in one of the stats. The issue happens when few time passes since we start the stat and we ask for data.
I added a Unit Test to check it does not happen again in the future.
Not needed.
=> Fix exceptions happening due to too high marker rates

erizo_controller/ROV/rovMetricsGatherer.js, erizo_controller/ROV/rovMetricsServer.js, scripts/licode_default.js
Added a prefix in prometheus stats to make them easier to manage. 
This PR also fixes a bad use of `collectDefaultMetrics `.
=> Added option to set a prefix for prometheus stats

erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js, scripts/licode_default.js
We've detected that there are times where ErizoJS processes won't stop when all publishers leave, causing problems when those processes stay up a long time processing many connections.
We're investigating the issue and will fix the root of the problem. 
This PR adds a protection for this problem by checking erizoJS processes that remain up after a long time since the first time they were active. It also makes sure that no new publisher or subscriber has been added recently. These parameters can be adjusted in `licode_config`.
=> Periodic task that checks uptime in erizoJS

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/utils/FunctionQueue.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Helpers.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/erizoJS/erizoJSController.js
Now that we started to unsubscribe and subscribe to streams in production we found some issues when using Single Peer Connection. This PR aims to fix several of this pending issues in different commits.
Not needed.
=> Fix negotiations by better protecting access to PeerConnection

erizo_controller/erizoController/models/Channel.js, erizo_controller/erizoController/models/Client.js, erizo_controller/test/utils.js
We've detected some instances where `Client` would process calls even after `Channel` has disconnected. This PR makes sure `Client` does not receive any events from `socket` when `disconnect` is called or when the `disconnect` event is fired.
=> Remove socket listeners on channel disconnect

erizo/src/erizo/dtls/DtlsClient.cpp
This fixes #1378 and #1373. We were still using DTLS 1.0
Not needed.
=> Update to 1.2 version of DTLS

erizo_controller/erizoClient/lib/state-machine.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/PeerConnectionFsm.js
This PR adds a finite state machine that tracks and protects all calls from baseStack to peerConnection.
This PR also reorganizes many of the functions in baseStack. There are now two structures `enqueuedCalls` and `protectedCalls`.
`protectedCalls` are only called from `PeerConnectionFsm`
`enqueuedCalls` can be called from anywhere else and they are protected by a `FunctionQueue`.
=> Added FSM to protect peerConnection use in basestack

erizo/src/erizo/dtls/DtlsClient.cpp
refer #1380 
`mContext = SSL_CTX_new(DTLSv1_2_method());`
Chrome under M74 （mine 版本 73.0.3683.75（正式版本） （64 位））got “message: Handshake failed, transportName:video, openSSLerror: error:1409210A:SSL routines:ssl3_get_server_hello:wrong ssl version”
ssl/ssl.h
const SSL_METHOD *DTLS_method(void); /* DTLS 1.0 and 1.2 */
should be ok
=> change DTLSv1_2_method to DTLS_method

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
I introduced an issue by which we were sending SDPs with sendonly in cases where we wanted to receive medias too. That's caused by the new policy of not creating SDP offers so often.
Not needed.
=> Fix audio issues caused by not creating offers

erizo_controller/erizoController/erizoController.js
This PR exits Erizo Controller process when there is a timeout trying to connect to Cloud Handler.
Not needed.
=> Kill Erizo Controller if CH is not reachable

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js
This PR fixes an issue that caused unsubscribes to the last stream in a connection to create a never ending loop of calls to removeStream.
=> Fix unsubscribe from the last stream in a connection

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/models/ErizoList.js, erizo_controller/erizoController/models/Room.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/test/utils.js
This PR allows connections (the PeerConnection-WebRTCConnection pair) to remain open while a client stays in a room in SinglePC. That means when unpublishing or unsubscribing from the last stream, the connection won't be immediately closed, allowing the client to publish/subscribe again without the added cost of creating a new Connection (ice negotiation, etc.)
This also changes the way ErizoJS processes are handled, they are not closed when the last publisher leaves, they are now notified when clients leave ErizoController and the process ends when the last client leaves.
=> Connections now persist with Clients when in singlePC

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.h, erizo/src/erizo/rtp/RtpExtensionProcessor.cpp, erizo/src/erizo/rtp/RtpExtensionProcessor.h
fix issue #1393 #1399 
add ExtensionId translator
Publisher：  translate external ExtensionId into internal ExtensionId 
Subscriber：translate internal ExtensionId into external ExtensionId
=> add ExtensionId translator

erizo_controller/erizoClient/src/Room.js
This PR fixed an issue that prevented unsubscribing from failed connections. This should be much more common in multiplePC.
Before this, we were waiting for the peerConnection event that could not arrive since the peerConnection had failed. That would block future subscriptions to that stream since it was never removed and was marked as `failed`.
Now, if the connection (stream) has failed, the unsubscribe will take place.
=> Emit stream-unsubscribed when callback is received and connection has failed

erizo_controller/erizoJS/models/Publisher.js
subscribers
`muteVideo` and `muteAudio` in the `Publisher` were not being updated if no subscribers are present. This caused publishers to remain in the same state even after a mute/unmute request
=> update muteVideo and muteAudio for publishers when there are no subscribers

erizo_controller/erizoClient/src/Room.js
This PR fixes a race condition that could take place when a (multiplePC) stream fails while unsubscribing from it. In that case, the stream would stay marked as `failed` and erizoClient would never allow subscribing to it again.
=> Check if already unsubscribing when ice fails

erizo/src/erizo/rtp/RtpH264Parser.cpp
This PR fix H264 keyframe parse error:
- if the packet is FU-A (fragmented nal) type
set keyframe flag to true when nal_type==5 and start_bit==1
- if the packet is STAP-A (one packet, multiple nals), sometimes the keyframe size is smaller than MTU, especially low resolution video, so publisher will put sps,pps and keyframe into one packet. need to parse it in such case.
parse all nals type and  set keyframe flag to true if one nal_type==5
=> Fix h264 keyframe parse error

erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/RtcpRrGenerator.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp
Another possible solution for the bandwidth estimation problems when not using simulcast in Chrome >72.
This PR drops all other RR packets from subscribers and relies on the sender estimation implementation in licode to update REMB from subscribers.
Also, this PR updated RR packets generated in Licode so the packets lost are monotonically increasing. There are different ways to do this but, at this time, we chose to use the packet loss ratio when it's > 0.
If tests are positive, in the future, we will work on separating the logic that decides what RR packets to forward in a new handler.
=> BWE Fixes for publisher estimation in chrome >72

doc/client_api.md, erizo/src/erizo/rtp/QualityManager.cpp, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
This PR adds a new option for the simulcast API. You can now set spatial layer bitrate limits in simulcast.
This PR also removes the 'fallback' we put in place for simulcast since it no longer works as expected. This fallback mechanism was used to keep receiving video data (and padding) to help the estimate recover when under the lowest simulcast layer. The recommended solution for now is to lower the bitrate of the lowest layer.
New parameter for simulcast configuration detailing the layers and the requested bitrate in bps.
=> Implement customizing bitrate layer for simulcast

erizo_controller/erizoJS/models/Publisher.js
We were not setting the maxVideoBW configuration when publishing in ErizoJS.
Not needed.
=> Set MaxVideoBW in ErizoJS when starting pub

erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/RtpVP9Parser.cpp
We were not setting pictureId and right TIDs and SIDs in VP9. There is still some work to do to fix SVC, but it is not a priority since it is not enabled by default in Chrome (we still need a magic argument).
Not needed.
=> Fix the way we detect layers in VP9 parser

erizo/src/erizo/rtp/FakeKeyframeGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpTrackMuteHandler.cpp, erizo/src/erizo/rtp/RtpTrackMuteHandler.h, erizo/src/test/rtp/RtpTrackMuteHandlerTest.cpp
This PR solves a race condition when muting video before receiving any keyframes. To solve this, this PR implements transforming all keyframes into black keyframes when muted (and using VP8).
Also, to solve possible problems when unmuting a video, it will wait until a keyframe comes to start forwarding video again.
=> Add Black keyframes in mute video

doc/client_api.md, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js
Add more info to the stream-failed event to know exactly the origin of the failure.
Not needed.
=> Add origin info to streamEvent failed

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo/src/erizo/media/ExternalInput.h, erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizo/src/erizo/media/MediaProcessor.cpp, erizo/src/erizo/media/MediaProcessor.h, erizo/src/erizo/media/SyntheticInput.cpp, erizo/src/erizo/media/SyntheticInput.h, erizo/src/test/OneToManyProcessorTest.cpp, erizo/src/test/utils/Mocks.h, erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js
This PR addresses a race condition when closing the `OneToManyProcessor` before its associated Publisher's `MediaStream`.
In order to do that, the `close` operation for all `MediaSink` and `MediaSources` now returns a `future` that can be used to make sure the operation is finished. Particularly in `MediaStream` that operation is async and runs in the Worker thread making the future very useful.
In ErizoAPI, now the `close` operation changes slightly and now returns a promise. That promise is used in `erizoJSController` to make sure the mediaStream for the publisher is closed before the muxer is closed.
=> Use promises when closing MediaStreams (and all sinks and sources)

utils/release.sh
Add docker latest tag when creating staging releases
Not needed.
=> Add docker latest tag when creating staging releases

erizoAPI/OneToManyProcessor.cc, erizoAPI/OneToManyProcessor.h
We were still using a raw pointer in ErizoAPI with OneToManyProcessor. This could potentially cause crashes with async operations since we had no way to protect the pointer. This PR changes this so the erizo object is managed as a shared_ptr in the same way we do with WebRTCConnection or MediaStream.
=> Use shared_ptr instead of raw pointer for erizo OTM in erizoAPI

erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js
This PR fixes two problems with `closeNode`:
1 - MediaStream close promise was not resolved because the `future_async_` was closed as part of the process, now the async will be closed after it notifies the completion of the task
2 - When WebRTCConnection is closed as part of closeNode because we're closing the last mediaStream in that connection, we would not resolve the `removeStream` promise. Now we make sure the stream is removed and the promise resolved before checking if we should close the connection
=> Fixed race conditions with promises when closing Nodes

erizo_controller/erizoClient/src/webrtc-stacks/PeerConnectionFsm.js
Log FSM issues as warnings since they are recoverable.
=> Use warning messages instead of errors

erizo_controller/erizoJS/models/Connection.js
We are seeing crashes because we are using destroyed OneToManyConnections. This PR aims to solve an obscure path that could lead to that scenario.
Not needed.
=> Wait for mediaStreams to be closed before removing them from the list in ErizoJS

erizo_controller/erizoJS/erizoJS.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/test/erizoJS/erizoJSController.js
This PR fixes #1432 
Not needed.
=> Fix wrong connectionIds when using multiple erizoJS processes

erizoAPI/MediaStream.cc, erizoAPI/WebRtcConnection.cc
Fix concurrency issues in MediaStream.cc when using NodeJs libuv.
Not needed.
=> Fix concurrency issues in ErizoAPI/MediaStream

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoJS/models/Connection.js, erizo_controller/test/utils.js
This PR addresses race conditions when getting and handling SdpInfo by making it run as an `asyncTask` in erizo. This involves also implementing a mechanism to return values when promises are resolved from ErizoAPI.
=> Make getLocalSdpInfo async

erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h
Avoid closing uv_async handle from threads other than the main uv loop.
@lodoyun can we do pair review for this PR on Monday?
Not needed.
=> Do not call uv_close from uv loop other than the main one

erizo_controller/erizoClient/src/Stream.js
We were printing the wrong data when access to media was rejected in the browser.
Not needed.
=> Log the right message when media is rejected

doc/client_api.md, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js
Adds a client API to update simulcast layer bitrate.
Note: It also fixes an issue with the updateConfiguration when run for publishers.
This is the new API in the cliend side.
```
localStream.updateSimulcastLayersBitrate({0: 80000, 1: 430000});
```
In this example we are configuring 2 spatial layers bitrates, limiting the lower layer to 80 Kbps and the higher to 430 Kbps.
=> Add a client API to update simulcast layer bitrate

erizo/src/erizo/WebRtcConnection.cpp, erizoAPI/WebRtcConnection.cc, erizo_controller/erizoJS/models/Connection.js
This PR fixes two possible crashes in the life of SdpInfo in getLocalDescription:
1. The path when we cannot call `getLocalSdpInfoSync` would crash because `this_ptr` would not be present.
2. We made the copy of SdpInfo when the promise is resolved in `ErizoAPI`, we could be potentially modifying that data structure in another thread at the same time.
=> Fix crashes when getting local sdp

erizoAPI/MediaStream.cc
This PR addresses an issue that affects the stats calls in ErizoJSController since potentially some of the promises for the stats call would not resolve.
This fixes an issue with Ackuaria not displaying stats for publishers in some situations.
We probably still need to investigate if this happens more than it should - the erizoAPI MediaStream structure still being alive while the erizo one is already destroyed.
=> Resolve getStats promise even if the MediaStream cannot be locked

erizoAPI/MediaStream.cc
If the underlying mediaStream is not present or has been closed, `getStats` was not calling back. This PR fixes this, avoiding keeping pending promises in `ErizoJS`
=> Call getStats callback even if mediaStream is not present or is closed

extras/basic_example/basicServer.js, nuve/nuveAPI/nuve.js, scripts/licode_default.js
This PRs gives more flexibility when executing Nuve and Basic Example.
Not needed.
=> Add Nuve and Basic Example ports to licode config

erizo/src/erizo/media/ExternalInput.cpp, erizo/src/erizo/media/ExternalInput.h, erizo/src/erizo/media/MediaProcessor.cpp, erizo/src/erizo/media/MediaProcessor.h, erizo/src/erizo/media/codecs/VideoCodec.cpp, erizo/src/erizo/media/codecs/VideoCodec.h, erizoAPI/ExternalInput.cc, erizoAPI/ExternalInput.h, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/utils/Random.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/erizoController/erizoController.js, erizo_controller/test/erizoController/roomController.js, erizo_controller/test/erizoJS/erizoJSController.js
ExternalInput code was outdated due to latest changes in code. This PR aims to fix most important issues I faced when trying to publish a RTSP flow.
Not needed.
=> Fix ExternalInput for RTSP sources

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/test/WebRtcConnectionTest.cpp
This PR adds a basic Pipeline to WebRtcConnection. The idea is to provide it with a tool to easily add more and more functionality to the connection/transport level. In the future we might decide for instance to move all the BWE logic to the connection better than having it in the MediaStream.
Not needed.
=> Add a basic pipeline to webrtcconnection

erizo/src/erizo/MediaStream.cpp
This bug affected bandwidth estimation in simulcast, slowing the process and preventing higher bitrate sometimes.
=> Put padding removal after bandwidth estimation in pipeline

erizo/src/erizo/MediaStream.cpp
Reduce Media Stream stats frecuency as it seems to reduce efficiency in DB queries.
Not needed.
=> Reduce MediaStream stats frequency

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/models/Connection.js
It seems that there is still some case where we are not setting Setup=actpass in the Erizo offers. This PR aims to fix those cases.
Not needed.
=> Ensure we use Setup actpass role when setting remote offers in ErizoClient

erizo_controller/ROV/rovMetricsGatherer.js, erizo_controller/erizoController/roomController.js
This bugs went past my tests of the StreamManager PR.
The list of publishers is not there anymore - ⚠️ this causes a crash in erizoController whenever an erizoJS stops responding.
Also, the stats are now fixed.
=> Fix log to use the new variable and fix stats

erizo_controller/erizoClient/src/utils/ConnectionHelpers.js
This PR enables the use of MediaDevices.getDisplayMedia() for screensharing. If an extensionId or desktopStreamId are specified in the Stream options, the GetUserMedia() method is still used. 
=> Enabling GetDisplayMedia for screensharing

erizo/src/erizo/rtp/StatsHandler.cpp
We were not updating stats about the REMB received by the subscribers. We now make use of the proper source identifiers needed for REMB packets.
Not needed.
=> Add remb value to subscriber stats

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimationHandler.h, erizo/src/erizo/rtp/StatsHandler.cpp, erizo/src/test/utils/Mocks.h
This PR moves the SenderBandwidthEstimationHandler to WebRtcConncetion to better estimate bandwidth when there are multiple streams involved.
Not needed.
=> Move SenderBandwidthEstimationHandler to WebRtcConnection

erizo_controller/erizoController/models/Client.js
This PR fixes an issue that caused removeSubscriptions not to work. The parameters were in the wrong order.
=> Fix arguments for removeSubscriber in removeSubscriptions

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/bandwidth/ConnectionQualityCheck.cpp, erizo/src/erizo/bandwidth/ConnectionQualityCheck.h, erizo/src/erizo/bandwidth/TargetVideoBWDistributor.cpp, erizo/src/erizo/bandwidth/TargetVideoBWDistributor.h, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp, erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h, erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizo/src/erizo/rtp/RtpPaddingManagerHandler.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimationHandler.h, erizo/src/test/WebRtcConnectionTest.cpp, erizo/src/test/bandwidth/TargetVideoBWDistributor.cpp, erizo/src/test/rtp/RtpPaddingGeneratorHandlerTest.cpp, erizo/src/test/rtp/RtpPaddingManagerHandlerTest.cpp, erizo/src/test/utils/Mocks.h, erizo/src/test/utils/Tools.h, erizo_controller/erizoAgent/log4cxx.properties, extras/basic_example/public/script.js
I'm moving the logic that decides whether to enable or disable padding to the WebRtcConnection. It will also decide how much bitrate will be used and will distribute it among the subscribed streams in the same single peer connection.
Not needed.
=> Add new Padding Manager in WebRtcConnection

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/rtp/PliPacerHandler.cpp, erizo/src/erizo/rtp/PliPriorityHandler.cpp, erizo/src/erizo/rtp/PliPriorityHandler.h, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/QualityFilterHandler.h, erizo/src/erizo/rtp/RtpUtils.cpp, erizo/src/erizo/rtp/RtpUtils.h, erizo/src/test/rtp/PliPriorityHandlerTest.cpp, erizo/src/test/utils/Tools.h, erizo_controller/erizoAgent/log4cxx.properties
This PR implements a handler that throttles PLI requests based on priority.
All PLI packets are marked with high or low priority. High priority PLIs go directly through the handler but low priority ones are throttled so only 1 is sent every 3 seconds.
Currently the only PLI packets that are marked as low priority are those requested when switching to a higher layer.
=> Implement Pli Priority Handler

.circleci/config.yml, Dockerfile, erizo_controller/ROV/rovMetricsGatherer.js
Here we will start to add more information to prometheus metrics:
- Commit short hash.
- Commit date.
- Public IP as we provide it in the config file or we obtain from AWS.
Not needed.
=> Add commit and public ip info to prometheus metrics

erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/rtp/RtpHeaders.h
We were modifying the wrong SSRC field in RTCP packets sent through the OneToManyProcessor's deliverAudioData.
Not needed.
=> Fix Audio SDES packets that were corrupted in OTM

erizo_controller/erizoJS/models/Connection.js
Fix Stats retrieved from Ackuaria when connection is closed
Not needed.
=> Fix Stats retrieved from Ackuaria when connection is closed

erizo/src/erizo/rtp/RtpExtensionProcessor.cpp
We were not updating absolute send time RTP extension because we were not using the translated extension id. The result was that we were having lower video quality.
=> Fix the way we detect abs send time to update it

erizo/src/erizo/OneToManyProcessor.cpp
We are having audio drifting because we are not correctly handling timestamps in video. This is a quick hack to avoid sending audio SRs properly and use a best effort approach when syncing audio and video in Chrome. 
Another better solution that updates timestamps in video SRs in Simulcast is coming.
Not needed.
=> Avoid audio drifting by updating audio SRs

erizo/src/erizo/rtp/StatsHandler.cpp
This PR is a small fix of the mechanism we use to use the maximum bandwidth available in the conneciton. We were counting padding as media bitrate, so it was used by the internal BW estimation to know the maximum bitrate we want to send, but padding bitrate should not be part of that equation.
Not needed.
=> Do not count padding bitrate as video bitrate stat

erizo/src/erizo/rtp/LayerDetectorHandler.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, extras/basic_example/public/quality_layers.js
We did not take into account constrains when calculating the target video bitrate in the BWE mechanisms.
I also fixed an issue by which we were not calculating the framerate properly.
Not needed.
=> Calculate target bitrate from max constrained layer

nuve/installNuve.sh
This PR forces the use of mongojs version 2.6. Nuve is not compatible with version 3.0.
=> Fix mongojs version used in nuve

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/rtp/PeriodicPliHandler.cpp, erizo/src/erizo/rtp/PeriodicPliHandler.h, erizo/src/test/rtp/PeriodicPliHandlerTest.cpp, erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizo_controller/erizoAgent/log4cxx.properties, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/test/utils.js
This PR optimizes the way we request keyframes when in slideshow. Instead of using an Interval in ErizoJS, this implements a handler in C++ erizo that periodically checks if a new keyframe is needed and requests it.
=> Add periodic Pli handler

erizo/src/erizo/rtp/PeriodicPliHandler.cpp, erizo/src/test/rtp/PeriodicPliHandlerTest.cpp
This PR fixes a bug where the periodicPliHandler would only request a PLI every other interval in ideal conditions.
=> Fix intervals in periodic Plis

erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/RtpHeaders.h
This PR updates Sender Reports in Simulcast by calculating the new timestamp. This is a solution better than the quick fix implemented yesterday.
Not needed.
=> Update RTCP SR timestamps in Simulcast

scripts/licode_default.js
`useNicer` is no longer needed.
=> Remove useNicer from licode configuration

erizo/src/erizo/rtp/RtcpAggregator.cpp, erizo/src/erizo/rtp/RtcpForwarder.cpp, erizo/src/erizo/rtp/RtcpProcessor.h, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimationHandler.h
There were still cases where the SenderBandwidthEstimationHandler was not calculating the bandwidth estimation properly. This PR fixes them. The problem was that we were updating the same estimator with RRs received from multiple streams.
Not needed.
=> Fix RR handling for SenderBWE

extras/docker/initDockerLicode.sh
Issue #1512 might be caused by a wrong network interface configuration. I added it also as an option when we run the docker image.
Not needed.
=> Add networkInterface as an option to docker run

erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h
This PR fixes some problems with the media_parameters negotiation. Before this, a codec that we didn't support parameters for could get in the negotiated payloadVector.
Furthermore, if several instances of the same codec but with different parameters and PT were in the offer, we would only keep the last PT
=> Fix PT negotiation with format parameters

erizo/src/erizo/dtls/DtlsSocket.cpp
We need to better handling SSL errors because we are now seeing some crashes in production after having updated to a newer OpenSSL version.
Not needed.
=> Better handling of SSL errors

erizo/src/erizo/rtp/RtpTrackMuteHandler.cpp, erizo/src/erizo/rtp/RtpTrackMuteHandler.h, erizo/src/test/rtp/RtpTrackMuteHandlerTest.cpp, erizo_controller/erizoClient/src/Stream.js
This PR addresses issues in TrackMuteHandler - particularly video issues:
1. Now we will only be able to mute video or audio tracks once the stream is published or subscribed. We allowed mutes before the pc was present, generating weird cases.
2. Once the video is muted we let a frame through periodically - transforming it into a black keyframe
3. Better manage sequence number by using translators instead of an offset.
=> Fix issues with video mute in trackMuteHandler

scripts/installUbuntuDeps.sh
Update conan to version 1.21. Previous version started to fail.
Not needed.
=> Update conan version to 1.21

erizo/src/erizo/SdpInfo.cpp, erizo/src/erizo/SdpInfo.h, erizo/src/erizo/WebRtcConnection.cpp, erizoAPI/ConnectionDescription.cc
Fixes #1466 
Firefox expects an answer with a=inactive when there is no audio or video in an SDP negotiation.
Not needed.
=> Fix audio/video only streams with Firefox

erizo_controller/test/erizoAgent/erizoAgent.js, erizo_controller/test/erizoController/erizoController.js, package-lock.json, package.json, scripts/installUbuntuDeps.sh
This PR updates `mocha` and `winston`, fixing some security warnings.
The new mocha version does not force exit once the tests are done - see [here](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit). We should investigate the root issue, in the meantime `--exit` can be used to get the old behavior.
This PR includes a fix so we can use args with mocha without breaking `ErizoController` and `ErizoAgent` tests.
=> Update mocha and winston

erizo/src/erizo/DtlsTransport.cpp
If transport_ can be null, transport_->getTransportState() should be called after the null check.
=> Add null check for transport.

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
There was an issue when unpublishing streams and then trying to subscribe to new ones beucase the negotiation got blocked. The problem was that we expected that Chrome called onnegotiationneeded after calling remoteStream.
Not needed.
=> Fix negotiation when removing streams

erizo/src/erizo/WebRtcConnection.cpp
We could be renegotiating RTP Extensions without updating streams properly. So we avoid that situation with this PR.
Not needed.
=> Skip extension renegotiations

erizo_controller/erizoClient/src/Room.js
Send SDP offers from Erizo by default. The other options will eventually be removed once this is used in production.
Not needed.
=> Send SDP Offers from Erizo by default

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js
This is specially useful when unsubscribing or unpublishing streams in Single Peer Connection. We could not find existing connections because they were not attached to any stream in some cases.
Not needed.
=> Improve the way we look for Erizo Client Connections internally

doc/client_api.md, erizo_controller/erizoClient/src/Erizo.js, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/utils/FunctionQueue.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
We have a new timeout for negotiations that get locked and we trigger a `connection-failed` when it happens.
I updated the client API with the new event.
=> Trigger connection-failed events when negotiation times out

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/rtp/QualityFilterHandler.cpp, erizo/src/erizo/rtp/StatsHandler.cpp
We have been seeing more reports of a/v desynchronization. This PR disables the mechanism we have been using to update timestamps in SRs and disables sending SRs from audio, relying on the client's best effort.
To track the problem this PR also adds stats for SRs timestamps and NTP.
=> Put back audio delay hack and add stats

erizo_controller/erizoController/erizoController.js
modify the  getopt's  bug,  port  listen_port  recording_path  can't get  from the   args
=> modify the getopt's bug,  in EC  module

erizo/src/erizo/OneToManyProcessor.cpp
I have seen a couple of crashes because of this bug. We are already checking for null pointers in other parts of this file.
Not needed.
=> Check for null pointers in OTM

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo/src/erizo/media/ExternalInput.h, erizo/src/test/OneToManyProcessorTest.cpp, erizoAPI/OneToManyProcessor.cc
There have been other crashes inside OneToManyProcessor when trying to access publisher's stuff.
Not needed.
=> Avoid using publisher from OTM

erizo/src/erizo/MediaDefinitions.h, erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/OneToManyProcessor.cpp, erizo/src/erizo/OneToManyProcessor.h, erizo/src/erizo/media/ExternalInput.cpp, erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/SyntheticInput.cpp, erizo/src/erizo/rtp/RtpSink.cpp, erizo/src/erizo/rtp/RtpSource.cpp, erizo/src/test/OneToManyProcessorTest.cpp, erizo/src/test/media/SyntheticInputTest.cpp, erizoAPI/ExternalInput.cc, erizoAPI/MediaDefinitions.h, erizoAPI/MediaStream.cc, erizoAPI/MediaStream.h, erizoAPI/OneToManyProcessor.cc, erizoAPI/SyntheticInput.cc, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Node.js, erizo_controller/test/utils.js
Introduce Weak pointers to Media Definitions to avoid having wrong access to memory from OneToManyProcessor.
Not needed.
=> User WeakPtr instead of raw pointers in MediaDef

erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Client.js, erizo_controller/test/erizoController/Client.js
There are race conditions between stream publishing and unpublishing. Similar things could happen for subscribing. It was actually affecting Ackuaria.
Not needed.
=> Fix race conditions between publish/unpublish

scripts/installUbuntuDeps.sh
This fixes an issue when building Licode because we can't download opus package from that URl anymore.
Fixes issue #1575 
Not needed.
=> Fix Opus download URL

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Socket.js
This PR adds two events that might be interesting when tracking WebSocket reconnections.
Not needed.
=> Emit re/connection events

erizo_controller/erizoController/erizoController.js
=> Wrong configuration item used

doc/docker.md
Fix doc issues commented in #1580 
Not needed.
=> Fix minor issues in docker docs

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js, erizo_controller/erizoJS/models/SessionDescription.js, extras/basic_example/public/script.js
This PR fixes two issues in Firefox:
- When negotiating SDPs when Erizo sends its Offer first (#1577)
- Simulcast was not working anymore due to an issue in the SDPSemantics.
Not needed.
=> Fix Firefox SDP negotiation and Simulcast

erizo_controller/erizoJS/models/Subscriber.js
`Subscriber` was always ignoring `MediaStreamEvents` because it was checking the wrong id. It should be checking the streamId in erizo
=> Fix stream used for check - should use the one for the stream in erizo

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Socket.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/utils/ConnectionHelpers.js, erizo_controller/erizoClient/src/utils/Logger.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FcStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js, erizo_controller/erizoClient/src/webrtc-stacks/PeerConnectionFsm.js
This PR adds Log scopes to make it easier to filter log lines in Erizo Client. We will now do it by module, and we are currently having one module per file (this could change in the future).
We don't change any public API, although people could set up different log levels for each module now.
For instance, we could do things like:
```js
Erizo.Logger.setLogLevel(Erizo.Logger.NONE);
Erizo.Logger.module('Stream').level = Erizo.Logger.DEBUG;
```
=> Use log modules in Erizo Client

extras/basic_example/basicServer.js
The default value for nuveUrl in `basicServer` is not the same that we have in `licode_default.js`. This one fails when trying to connect to nuve
=> Fix default nuveUrl

extras/basic_example/basicServer.js, extras/basic_example/log4js_configuration.json, extras/basic_example/package-lock.json, extras/basic_example/package.json, scripts/licode_default.js
This PR adds some logging options for basicExample.
=> Added  logging for basicExample

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/bandwidth/ConnectionQualityCheck.cpp, erizo/src/erizo/rtp/RtcpFeedbackGenerationHandler.cpp, erizo/src/erizo/rtp/RtcpFeedbackGenerationHandler.h, erizo/src/test/fallback/ConnectionQualityCheckTest.cpp, erizo/src/test/utils/Mocks.h
We now only measure the fraction lost in the subscriber's path, by subtracting the fraction lost measured in the publisher's side when calculating it in ConnectionQualityCheck.
Not needed.
=> Add SR info to algorithm in ConnectionQualityCheck

erizo_controller/erizoClient/src/Stream.js
We've seen instances where the `removeChild` call issued when stopping a `VideoPlayer` or `AudioPlayer` throws an exception. This PR catches that exception and logs it, preventing it from altering the rest of the operations. It's pretty safe since that exception should be thrown when the child has already been removed.
=> Catch the exception if the player dom element fails when being removed

erizo/src/erizo/MediaStream.cpp, erizo_controller/common/logger.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoController/models/Room.js, erizo_controller/erizoController/roomController.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Node.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/test/utils.js, nuve/nuveAPI/mdb/tokenRegistry.js
Add more info to logs about metadata and options.
Not needed.
=> Add more info to logs

extras/basic_example/public/script.js
This PR cleans up the way we get configuration flags in the BasicExample by creating a new global structure to hold them and parsing all of them when the window is loaded.
=> Centralize the way we get configuration flags in BasicExample

erizo_controller/erizoJS/models/Connection.js
There was an issue by which we were not triggering Connection Quality Levels. We need to initialize a variable.
Not needed.
=> Initialize timer to trigger connection quality level events

erizo/src/erizo/dtls/DtlsClient.cpp
This should fix issues with latest versions of Chrome (v86+), like the one mention in #1609 .
Not needed.
=> Update x509 cert version to 3

doc/client_api.md, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Stream.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
New Client API to update active simulcast layers for publishers.
We can now decide which Simulcast layers are active. It can only be applied to publishers.
```
localStream.updateSimulcastActiveLayers({0: true, 1: false});
```
In this example we are configuring 2 spatial layers bitrates, limiting the lower layer to 80 Kbps and the higher to 430 Kbps.
=> New Client API to update active simulcast layers for publishers

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/rtp/QualityManager.cpp
This PR adds stat to track QualityLevel.
=> Add qualityLevel stat

erizo/src/erizo/rtp/QualityManager.cpp
This PR adds a check to make sure that the `QualityManager` is initialized before inserting stats
=> Fix crash while updating quality stats

erizo/src/erizo/NicerConnection.cpp, erizo_controller/erizoAgent/erizoAgent.js, erizo_controller/test/erizoAgent/erizoAgent.js, scripts/licode_default.js
This adds nICEr logs to the rest of ErizoJS logs to have more data in case of issues.
Not needed.
=> Print nicer logs

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/utils/FunctionQueue.js, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, extras/basic_example/public/script.js
This PR adds more info when Room objects dispatch a connection-failed event.
Not needed.
=> Add more info with connection-failed events

erizoAPI/MediaStream.cc, erizoAPI/WebRtcConnection.cc, erizo_controller/erizoClient/src/webrtc-stacks/PeerConnectionFsm.js
There was a long delay of some seconds between a promise was resolved and the corresponding listeners were triggered in ErizoAPI. This fix aims to force those triggers to complete Promise resolving quicker.
Not needed.
=> Force v8 promise resolving to publish/subscriber faster

erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoClient/src/Stream.js
This PR fixes a couple of problems introduced recently in logs.
1. Fix the _Connecting to Room_ log. It now properly logs the token and we remove the RoomId since it is never present and it can be confusing.
2. Logs would produce an error if a stream does not have attributes
=> Fix problems with logs

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/dtls/DtlsClient.cpp, erizoAPI/MediaStream.cc, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Publisher.js, erizo_controller/erizoJS/models/Subscriber.js, test/negotiation/utils/ClientStream.js, test/negotiation/utils/NegotiationTest.js
I'm currently investigating cases of unsubscriptions that finish with a timeout between ErizoController and ErizoJS. While investigating those cases I found out some minor leaks and tried to optimize some logic paths.
I think it is important to look into what I'm doing when closing the WebRtcConnection because we now use a promise to do it. I've tested it locally and I'm considering testing it in a dev environment with multiple browsers.
I'm also thinking of implementing async/await instead of chaining promises, but I'll do it in a different PR.
Not needed.
=> Fix memory leaks and optimize code

erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/NodeManager.js, erizo_controller/erizoJS/models/PublisherManager.js, erizo_controller/test/erizoController/Client.js, erizo_controller/test/erizoController/erizoController.js, erizo_controller/test/erizoJS/erizoJSController.js
This PR changes the way `removeClient` works in erizoJS. 
Before, when a Client left, erizoController would issue the commands to erizoJS to remove all published streams and subscriptions from that particular Client and then it would request the removal of the client itself. This approach lent itself to a number of race conditions.
With this PR, erizoController will only have to request the removal of the Client and only remove locally the data structures associated with that client (published and subscribed streams). ErizoJS will now process this removeClient as a command to remove the subscriptions and the published streams in the same operation.
The new `NodeManager` makes it easier for erizoJS to find published streams owned by a Client.
**Changes in Client or Server …
=> Update remove client in erizoJS

erizo/src/erizo/thread/ThreadPool.cpp, erizo/src/erizo/thread/ThreadPool.h, erizo/src/erizo/thread/Worker.cpp, erizo/src/erizo/thread/Worker.h, erizoAPI/ThreadPool.cc, erizoAPI/ThreadPool.h, erizo_controller/erizoJS/erizoJSController.js
We wanted to add even more information about the tasks that are being run within Erizo's Workers. I also added more data about the time it takes for these tasks to be completed.
Not needed.
=> Add stats about the delay added to running tasks in Workers

erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Events.js, erizo_controller/erizoClient/src/Room.js
This PR adds more info about the connection when a Stream failed because the ICE connection failed.
Not needed.
=> Add more info to StreamFailed events

erizo_controller/erizoJS/erizoJSController.js, erizo_controller/test/erizoJS/erizoJSController.js
This is a small PR to implement two small fixes:
- We were not populating Prometheus metrics about promises when there were no connections/streams.
- We were having some warnings when running tests.
Not needed.
=> Two minor fixes in metrics and tests

erizo_controller/erizoController/models/Client.js
Fixes a typo when calling the logger API.
Not needed.
=> Fix a typo when calling to logger API

extras/basic_example/public/script.js, scripts/initLicode.sh
This PR enables Simulcast, Single Peer Connection, and Offers From Erizo by default when using the basic example. They can be disabled manually with the corresponding URL queries set to 0. For example, if we want to disable Simulcast we would use this URL: `https://<licode_url>/?simulcast=0`.
I'm also adding some delay after starting RabbitMQ because it was failing to me almost 100% of the time.
Not needed.
=> Enable basic features by default in basic example

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
When adding or removing multiple streams, the connection level video and audio flags are not valid when trying to decide if we should trigger a new offer.
This PR takes into account the amount of video and audio tracks that have been modified to trigger `createOffer`.
=> Fix addStream not triggering createOffer

erizo_controller/initErizo_agent.sh
**Fixed init script for Ubuntu 20.04**
Fixed a problem in Ubuntu 20.04 where it didn't find libraries in folder /build/libdeps/build/lib
No changes
=> Fixed installation in Ubuntu 20

erizo/src/erizo/media/Depacketizer.cpp
after calling reset last_payload_ is null_ptr, so it is crashing.
=> Fix a crash in depacketizer that happened when we reset it

erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
This PR fixes an issue caused by Firefox behaving differently than Chrome when issuing `onnegotiationneeded`. Chrome calls it once per track in the stream while Firefox seems to call it only once per stream. This was causing issues in all Firefox connections.
=> Fix Firefox onnnegotiation needed

nuve/nuveAPI/mdb/dataBase.js, nuve/nuveAPI/mdb/erizoControllerRegistry.js, nuve/nuveAPI/mdb/roomRegistry.js, nuve/nuveAPI/mdb/serviceRegistry.js, nuve/nuveAPI/mdb/tokenRegistry.js, nuve/nuveAPI/test/mdb/dataBase.js, nuve/nuveAPI/test/mdb/erizoControllerRegistry.js, nuve/nuveAPI/test/mdb/roomRegistry.js, nuve/nuveAPI/test/mdb/serviceRegistry.js, nuve/nuveAPI/test/mdb/tokenRegistry.js, nuve/nuveAPI/test/utils.js, nuve/package.json
We were stuck in versions of MongoDB < 4.2 because we were using the eval function, which had been deprecated. This PR adapts the code to use the newer transactions.
Not needed.
=> Update Nuve MongoDB client

erizo_controller/ROV/rovMetricsGatherer.js, erizo_controller/ROV/rovMetricsServer.js, erizo_controller/erizoJS/erizoJSController.js
Add stats about ErizoJS Event Loop lag.
Not needed.
=> Add stats about erizoJS event loop lag

scripts/installNuve.sh, scripts/licode_default.js
This PR updates the default config file and the nuve installation script to adapt to the new format for the mongodb url.
=> Fix new url format for mongodb

erizo_controller/ROV/rovMetricsGatherer.js, erizo_controller/common/PerformanceStats.js, erizo_controller/common/amqper.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Connection.js, erizo_controller/erizoJS/models/Subscriber.js, erizo_controller/log4js_configuration.json, erizo_controller/package-lock.json, erizo_controller/package.json, erizo_controller/test/erizoJS/erizoJSController.js, erizo_controller/test/utils.js, package-lock.json, package.json
Add perf metrics about ErizoJS (requests to subscribe and unsubscribe streams) and export them to Prometheus through ROV.
This PR adds the structure needed to seamlessly add new metrics about the duration of tasks performed in ErizoJS and I add use it to calculate the performance of subscriptions/unsubscriptions.
Not needed.
=> Add Performance Metrics about ErizoJS to Prometheus

erizo/conanfile.txt, erizo/src/CMakeLists.txt, erizo/src/erizo/CMakeLists.txt, scripts/installMacDeps.sh
This PR addresses issues I experienced when linking against some boost dependencies: bzip2 and zlib.
We no longer need to use  `@conan/stable` for things that are in the Conan Index.
Additionally, I remove the conan brew installation for mac, that is not needed anymore.
=> Fix linking with bzip and zlib2 when building erizo

erizo_controller/erizoController/models/Client.js
This PR fixes a race condition by properly updating the `Client` in ErizoController when `setStreamPriorityStrategy` is called.
=> Update client with setStreamPriorityStrategy

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/bandwidth/StreamPriorityBWDistributor.cpp, erizo/src/erizo/bandwidth/StreamPriorityBWDistributor.h, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizo/src/test/bandwidth/StreamPriorityBWDistributor.cpp
bitrate
This PR addresses an issue where erizo would keep generating padding unnecessarily when using the `StreamPriorityBWDistribution`.
If the distributor does not use all the available bitrate, the `PaddingManager` would still assign padding bitrate to the mediaStreams. We don't actually need that since the distributor has already assigned all the needed bitrate according to the defined strategy.
This PR addresses this by instructing the `PaddingManager` to stop generating padding when there's unneeded available bitrate after a pass of the distribution algorithm.
=> Stop padding if the distributor does not assign all the available

erizo_controller/erizoClient/src/Room.js
This PR adds some protections when we subscribe, unsubscribe and unpublish streams.
=> Add protections when unpublishing, subscribing and unsubscribing streams

erizo/src/erizo/rtp/QualityManager.cpp
This PR fixes a bad check in QualityManager to avoid calling `enableSlideshowBelowSpatialLayer` if the new call does not change the configuration
=> Properly check is slideshow is enabled in QualityManager

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/test/utils/Mocks.h
Remove some old code from QualityManager that was affecting the new Stream Prioritization code:
- QualityManager did not enable padding anymore, so I removed that code.
- ConnectionQualityCheck will not affect QualityManager anymore. We saw weird and complex behavior due to spurious packet losses.
Not needed.
=> QualityManager cleanup

erizo/src/erizo/rtp/RtpVP8Parser.h, erizo/src/erizo/rtp/RtpVP9Parser.h, erizoAPI/binding.gyp
This fixes an issue that created problems when compiling ErizoAPI in mac with the last xcode update.
=> Fix typedef structs and compiler version for erizoAPI

erizo/src/erizo/bandwidth/BwDistributionConfig.h, erizo/src/erizo/bandwidth/StreamPriorityBWDistributor.cpp, erizo/src/erizo/rtp/QualityManager.cpp, erizo/src/erizo/rtp/QualityManager.h, erizo/src/erizo/stats/StatNode.cpp, erizo/src/erizo/stats/StatNode.h, erizo/src/test/bandwidth/StreamPriorityBWDistributor.cpp
This PR improves the use of stats in `StreamPriorityBandwidthDistributor` by:
1. Updating the stats stored in MediaStream more often (every 100ms at most)
2. Improving the stats stored in MediaStream so not only the last 500ms are taken into account but using the highest value for each second inside the 3 second window we are currently using
3. Adding to the calculated desired bitrate the same offset used in `QualityManager`
This PR also updates the tests accordingly. 
=> Adjust bandwidth estimation stats for stream priority distributor

erizoAPI/MediaStream.cc
This PR fixes an issue where a mediaStream would be initialized with an empty string when no priority is passed to erizoAPI constructor
=> Fix mediaStream priority initialization

erizo/src/erizo/WebRtcConnection.cpp, erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js, erizo_controller/erizoJS/models/Client.js
We were not handling MIDs properly when the media section was reused. And that affected cases where clients republished their streams.
I also removed a couple of annoying things related to logs and repeated negotiation attempts that were always failing.
Not needed.
=> Fix stream republishing

erizo_controller/erizoClient/src/Stream.js
This addresses an unintended change in behaviour in updatesimulcastlayersbitrate. If we explicitly pass `undefined`, now the `maxVideoBW` will be assigned, which is the closest to what it meant before the maxVideoBW changes.
=> Take into account passing "undefined" in updatesimulcastlayersbitrate

extras/basic_example/public/index.html, extras/basic_example/public/script.js
I added more options to the Basic Example to give more flexibility when publishing and subscribing.
Not needed.
=> Update Basic Example with more options

erizo_controller/erizoClient/src/Stream.js
This PR fixes 2 issues:
1. `updateSimulcastLayersBitrate` could update the structure passed as parameters if the bitrate specified was over the max. This could cause problems in the application if it happened to repeatedly use the same structure.
2. We were not updating the layers properly when setting MaxVideoBW. That could lead to a case where some of the layers did not comply with the maxVideoBW. 
=> Fix issues with setMaxVideoBW and updateSimulcastLayersBitrate

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/WebRtcConnection.h, erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizoAPI/WebRtcConnection.cc, erizoAPI/WebRtcConnection.h, erizo_controller/erizoClient/src/Room.js, erizo_controller/erizoController/erizoController.js, erizo_controller/erizoController/models/Client.js, erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js, erizo_controller/erizoJS/models/RTCPeerConnection.js, erizo_controller/erizoJS/models/WebRtcConnection.js, erizo_controller/test/utils.js
This PR implements a way to set a `target bandwidth` for connections in Licode. This target can be set with as part of a strategy as `connectionTargetBw` or by calling  `room.setConnectionTargetBandwidth` in the client.
The main use of target bitrate is to provide a goal or a target for the bandwidth estimation. Licode will generate padding to try to reach the target bitrate.
=> Implement target connection bandwidth

erizo_controller/erizoController/models/Client.js
This PR fixes cases where the connectionTargetBw was not being properly taken from the strategy definition
=> Fix initializing connection target bw

erizo_controller/erizoJS/erizoJSController.js, erizo_controller/erizoJS/models/Client.js
This PR aims to fix a crash when exiting ErizoJS after all clients leave.
The crash is caused by a race condition when connections are not closed properly.
=> Close all connections before exiting erizoJS

erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizo/src/erizo/rtp/RtpPaddingManagerHandler.h, erizo/src/test/rtp/RtpPaddingManagerHandlerTest.cpp
This PR introduces improved backoff and ramp up periods for `RtpPaddingMangerHandler`, the goal is for the manager to avoid congesting the network whenever possible.
It only takes into account differences in bandwidth estimation. If the estimation decreases, it is detected as potential network problems and padding will stop for some time. After that backoff period, it will gradually ramp up (if the estimation does not decrease again) until it sends the calculated `target_padding_bitrate`.
=> Add Backoff and ramp up periods in padding manager

erizo_controller/erizoClient/src/ErizoConnectionManager.js
Properly capture the `failed` message from the connection and emit a `connection-failed` event.
=> Fix connection failed event 

erizo/src/erizo/LibNiceConnection.cpp
This PR introduces a hack to fix [this issue](https://gitlab.freedesktop.org/libnice/libnice/-/issues/69) until we can use an updated version of libnice with [this fix](https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/182).
In short, when connecting with Chrome and libnice with `ice-lite` there's a change we're not passing any remote candidates to libnice because they are mdns candidates and they are not valid. Instead of resolving those candidates (which may not always work), this hack just passes a "dummy" candidate to get libnice to progress to the next state.
=> Hack to avoid make sure we pass candidates in libnice even when there's only mdns

nuve/nuveAPI/resource/roomsResource.js, nuve/nuveAPI/test/resource/roomsResource.js
We were having race conditions when creating a room from two different endpoints at the same time. This PR gives the option to reuse rooms with the same name when we call createRoom() to simplify other's codebases.
N/A
=> Give the option to reuse rooms with the same name

erizo/src/erizo/MediaStream.cpp, scripts/installUbuntuDeps.sh
`enableFallbackBelowMinLayer` and `enableSlideshowBelowMinLayer` are called from `StreamPriorityBWDistributor` in the `WebRtcConnection` thread. It is possible for the asyncTask in `MediaStream` to make those calls when the pipeline is already close but the `MediaStream` has not been destroyed yet. This results in a crash since it will end up calling `selectLayer` in `QualityManager` that tries to access the already removed pipeline directly.
=> Fix crash when calling enableFallback/Slideshow below min layer

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizo/src/erizo/rtp/StatsHandler.cpp
This PR solves a potential issue when deciding which streams will send padding. The PaddingManager now filters and only assigns bitrate to those subscribed streams that have video that is not muted.
This PR also adds logs to keep track of packets received and sent per SSRC while also accounting for the video bitrate with or without padding.
=> Add packet stats and improve padding bitrate assignment

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/MediaStream.h, erizo/src/erizo/bandwidth/StreamPriorityBWDistributor.cpp, erizo/src/test/bandwidth/StreamPriorityBWDistributor.cpp, erizo/src/test/log4cxx.properties
I was not taken into account if we distributed BW into layers but with not enough bandwidth to send the very first temporal layer.
Not needed.
=> Notify about low conn quality levels if bw is not enough for first layers

erizo_controller/erizoJS/models/Publisher.js
Recording was broken in the latest version of Licode. When trying to record the following error happened:
[erizo-0748cec0-2097-34c0-614a-5c62adf86945] 2022-01-14T10:50:34.332  - INFO: Publisher - message: Adding ExternalOutput, id: /tmp/331516203452821600.mkv_754069268214465700, url: /tmp/331516203452821600.mkv, state: erizo, data: true, audio: true, video: true, label: fpf1k0FCuYrewAYWb5IP07gu3ZPayyeHmvWy, screen: false, attributes: {}, metadata: {type: publisher}, muteStream: {audio: false, video: false}, encryptTransport: true, handlerProfile: {}, minVideoBW: 0, maxVideoBW: 300, mediaConfiguration: default, singlePC: false, streamPriorityStrategy: false, connectionTargetBw: 0, publicIP: 138.4.7.37, privateRegexp: {}, isRemote: true type: publisher …
=> Fix to recording

erizo/src/erizo/MediaStream.cpp, erizo/src/erizo/rtp/QualityManager.h
We were disabling padding (the target bitrate is the bitrate sent) when in slideshow below_min_layer. That can cause streams to be locked in that state without having a chance to recover and actually receive the spatial layer.
=> Enable padding when in slideshow below_min_layer

.circleci/config.yml
The images we were using for building in circleCI were deprecated. 
Updated them according to [this thread](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#deprecated-images-3)
=> Update circleCi image

erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/erizo/rtp/SenderBandwidthEstimationHandler.h
When in SinglePC we usually have multiple streams in one connection. This simple PR updates the min sending bitrate according to the number of streams.
=> Adjust min bitrate with the number of streams

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/erizo/rtp/RtpPaddingManagerHandler.cpp, erizo/src/erizo/rtp/RtpPaddingManagerHandler.h, erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp, erizo/src/test/rtp/RtpPaddingManagerHandlerTest.cpp
This PR implements a new algorithm to decide the amount of padding to send.
The new algorithm is based on a FSM with 4 states:
* `Start` - a ramp-up state where we will send more padding than the current estimate. This state will be triggered when a stream starts and will last for a few seconds.
* `Stable` - a mode similar to the old algorithm that adjust padding based on the current estimate, the target bitrate and the media that is being sent.
* `Hold` - After a big drop in estimate is detected, we will go into hold mode and stop sending padding for a few seconds.
* `Recover` - After being on hold, this state will check if the estimate drop was transitory by adjusting padding with the estimate detected before the drop. If another drop is detected in this state, the new …
=> Implement new padding manager calculation algorithm

erizo/src/erizo/media/ExternalOutput.cpp, erizo/src/erizo/media/ExternalOutput.h, erizoAPI/ExternalOutput.cc
There was an error where when recording where the recording would not stop and files kept growing even though licode gave no error.  What I found is that the promise that removed the ExternalOutput was always pending and never resolved and the callback was never executed but, the recording would stop on most occasions. After removing the lines shown in the PR the callback is always called and the recording stops all the times I tested it. 
To check this you check that the log inside the callback in the removeExternalOutput() function on line 115 of erizo_controller/erizoJS/models/Publisher.js is never reached. 
I don´t know the root issue of this problem, and my manual testing is limited so this might cause other issues with removing that check. I will leave this PR as a draft, as a point …
=> Fix recording not stopping

erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp
The result for the calculation for the last padding packet in a burst could result below 0 when the remaining padding bytes are less than the header size in bytes.
This could create problems down the line.
=> Avoid generating malformed padding packets

erizo/src/erizo/WebRtcConnection.cpp, erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp, erizo/src/third_party/webrtc/src/webrtc/modules/remote_bitrate_estimator/overuse_estimator.cc, erizo/src/third_party/webrtc/src/webrtc/modules/remote_bitrate_estimator/overuse_estimator.h
We've detected some crashes from the overuse estimator covariance matrix not being positive semi-definite. To prevent more crashes, this PR restarts the matrix every time this happens instead of crashing and generating dump. It also adds logs so we can further diagnose the problem and fix the root issue.
=> Fix overuse estimator crash

erizo/src/erizo/WebRtcConnection.cpp, erizo_controller/erizoClient/src/ErizoConnectionManager.js, erizo_controller/erizoClient/src/Room.js
In the latest chrome versions we've detected that `onremovestream` is not triggered even when the negotiation removing the stream is successful. Since that event is deprecated, this PR listens to `onremovetrack` and acts when all tracks in the MediaStream have been remove sending a `stream-removed` event that we use to trigger Licode's `stream-unsubscribed`.
This PR also replaces onstreamadded (which is also deprecated but still works) and uses `ontrack` 
=> Use ontrack and onremovetrack instead of onaddstream and onremovestream
