- package.json
update karma-requirejs from ~0.1.0 to ~0.2.0 to satisfy karma@0.10.10
> PR for issue #305

- erizo/src/erizo/SdpInfo.cpp
Fixes: Although the original issue was worked around with commit c07f1d46177d0e642a51e21ca761454259997d72, that commit fixes the issue at the client side and not the server side. This fix will allow Erizo to properly parse SDPs natively from Firefox 37 and up
Use Case: We use Licode server as our backend but we do not use the Licode client side.
> Moved the mapping of rtcp-fb lines till after we build a rtpmap vector

- scripts/installUbuntuDepsUnattended.sh
check if components are already installed. Do nothing in that case
> installUbuntuDepsUnattended.sh

- scripts/installCentOsDepsUnattended.sh
Not sure if this would be useful to you, but we use CentOS and made this change in order to automate the install.  
Cheers,
Forest
> Added a script to allow for unattended CentOS installation.

- scripts/installUbuntuDeps.sh
- scripts/installUbuntuDepsUnattended.sh
I had an issue installing libnice from http. I changed it to https.
> changed libnice source from http to https

- erizo_controller/erizoClient/src/Room.js
> Bugfix in Room.js if p2p = true

- erizo_controller/erizoClient/src/Stream.js
check if is p2p and handle the pc in the correct way
> BugFix in Stream.js updateConfiguration in p2p

- nuve/nuveAPI/cloudHandler.js
addedd hostname, port, ssl that prevent the function to work.
> missing parameters in addNewAmazonErizoController

- erizo/src/erizo/media/ExternalInput.cpp
This include allowed me to build successfully on CentOS 7
> Added libavutil/time.h

- nuve/nuveClient/src/N.API.js
necessary because the code is run in strict mode.
> fix missing variable declarations

- erizo_controller/erizoClient/src/views/AudioPlayer.js
- erizo_controller/erizoClient/src/views/Bar.js
- erizo_controller/erizoClient/src/views/VideoPlayer.js
adding sensible classes allows for easier theming of multiple players.
> classes for audio/video player and bar

- scripts/installMacDeps.sh
- scripts/installTravisDeps.sh
- scripts/installUbuntuDeps.sh
- scripts/installUbuntuDepsUnattended.sh
openssl 1.0.1l is the version that Node 0.10.37 uses
> Update openssl to 1.0.1l

- nuve/nuveAPI/auth/nuveAuthenticator.js
- nuve/nuveAPI/logger.js
- nuve/nuveAPI/mdb/roomRegistry.js
- nuve/nuveAPI/mdb/serviceRegistry.js
- nuve/nuveAPI/mdb/tokenRegistry.js
- nuve/nuveAPI/resource/roomResource.js
- nuve/nuveAPI/resource/roomsResource.js
- nuve/nuveAPI/resource/serviceResource.js
- nuve/nuveAPI/resource/servicesResource.js
- nuve/nuveAPI/resource/tokensResource.js
- nuve/nuveAPI/resource/userResource.js
- nuve/nuveAPI/resource/usersResource.js
- nuve/nuveAPI/rpc/rpc.js
- nuve/nuveAPI/rpc/rpcPublic.js
> Fixed log format in Nuve

- nuve/nuveAPI/test/rpc/rpc.js
Create UT for latest Nuve crash #569
> Create UT for latest Nuve crash

- _config.yml
- _layouts/default.html
- licode/contribute.html
This adds some guidelines to start contributing code/docs/reviews/etc. to the community.
Feel free to comment anything.
> [DOC] Add a new Contributor Guide

- erizo_controller/erizoController/erizoController.js
Allows more flexibility for event consumption
> Add user attributes in connection events

- .travis.yml
- erizo/src/CMakeLists.txt
- erizo/src/erizo/CMakeLists.txt
- erizoAPI/binding.gyp
- scripts/installTravisDeps.sh
- scripts/installUbuntuDeps.sh
- scripts/installUbuntuDepsUnattended.sh
> Use gcc/g++ 5 in ubuntu

- erizo/src/erizo/DtlsTransport.cpp
- erizo/src/erizo/DtlsTransport.h
- erizo/src/erizo/MediaDefinitions.h
- erizo/src/erizo/Transport.h
- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/WebRtcConnection.h
- erizo/src/erizo/pipeline/Handler.h
- erizo/src/erizo/pipeline/HandlerContext-inl.h
- erizo/src/erizo/pipeline/HandlerContext.h
- erizo/src/erizo/pipeline/Pipeline-inl.h
- erizo/src/erizo/pipeline/Pipeline.cpp
- erizo/src/erizo/pipeline/Pipeline.h
- erizo/src/erizo/rtp/RtpExtensionProcessor.cpp
- erizo/src/erizo/rtp/RtpExtensionProcessor.h
- erizo/src/erizo/rtp/RtpPacketQueue.h
- erizo/src/erizo/rtp/RtpRetransmissionHandler.h
This PR adds a new way to include functionality inside Erizo. It's based on a Pipeline with Handlers that could create/read/update/delete inbound and outbound RTP Packets.
> Add a pipeline with handlers inside WebRtcConnection

- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/rtp/RtpRetransmissionHandler.cpp
- erizo/src/erizo/rtp/RtpRetransmissionHandler.h
- erizo/src/test/rtp/RtpRetransmissionHandlerTest.cpp
Work in progress. I'm still adding unit tests for the new functionality, but I thought it would be interesting to create the PR already to discuss the solution.
> Add support to retransmit packets in Erizo

- erizo_controller/erizoJS/adapt_schemes/notify-break-recover.js
- erizo_controller/erizoJS/adapt_schemes/notify-break.js
- erizo_controller/erizoJS/adapt_schemes/notify-slideshow.js
- erizo_controller/erizoJS/adapt_schemes/notify-stop-feedback.js
- erizo_controller/erizoJS/adapt_schemes/notify.js
Last "cosmetic fix" was a non-cosmetic unfix.
> Now adaptation interval will properly stop when webrtconnection is close

- erizo_controller/erizoJS/erizoJSController.js
We should now always have an status: 105 message when connections are closed.
Regarding the implementation, I'm beginning to think we should wrap the addon.WebRTCConnection object in JS and explicitly add the context to it. Init and close should be functions of that object. What we have now is a little awkward.
> Added status log when closing WebRTCConnections

- erizo/src/erizo/DtlsTransport.cpp
- erizo/src/erizo/DtlsTransport.h
- erizo/src/erizo/Transport.h
- erizo/src/erizo/thread/Scheduler.cpp
- erizo/src/erizo/thread/Scheduler.h
- erizo/src/erizo/thread/ThreadPool.cpp
- erizo/src/erizo/thread/ThreadPool.h
- erizo/src/erizo/thread/Worker.cpp
- erizo/src/erizo/thread/Worker.h
- erizo/src/test/rtp/RtpRetransmissionHandlerTest.cpp
- erizo/src/test/thread/SchedulerTest.cpp
This PR adds a new Scheduler to Workers, to be able to schedule tasks that we want to execute in the future. It's interesting to create periodic tasks, timeouts, etc.
> Added a Scheduler to run tasks at a given time

- nuve/nuveAPI/test/cloudHandler.js
- nuve/nuveAPI/test/utils.js
This error comes from PR #507 that changes a library. Now the use of such library is protected.
> Fix Nuve tests

- scripts/installMacDeps.sh
- scripts/installTravisDeps.sh
- scripts/installUbuntuDeps.sh
libnice 0.1.13 was causing connection problems in some cases - We'll downgrade to 0.1.7 as it has proven to work without problems until we further investigate the issue
> Change libnice to v 0.1.7

- feature-review/single-peer-connection.md
In this PR I want to propose to change our current approach to support Single Peer Connections.
Main advantage: reduce usage of UDP ports and time to subscribe to new streams.
Please, provide as much feedback as possible to this proposal!!
> [FEATURE-REVIEW] Single Peer Connections

- nuve/installNuve.sh
- scripts/installErizo.sh
fix for a fresh install using nvm
> Fix install scripts for nvm

- scripts/installMacDeps.sh
- scripts/installUbuntuDeps.sh
- scripts/travisInstallDeps.sh
Another fix for the nvm install
> Fixed install scripts when LIB_DIR does not exist

- nuve/nuveAPI/ch_policies/default_policy.js
- nuve/nuveAPI/cloudHandler.js
- nuve/nuveAPI/mdb/dataBase.js
- nuve/nuveAPI/mdb/erizoControllerRegistry.js
- nuve/nuveAPI/mdb/roomRegistry.js
- nuve/nuveAPI/resource/usersResource.js
- nuve/nuveAPI/test/ch_policies/default_policy.js
- nuve/nuveAPI/test/cloudHandler.js
- nuve/nuveAPI/test/mdb/erizoControllerRegistry.js
- nuve/nuveAPI/test/mdb/roomRegistry.js
- nuve/nuveAPI/test/resource/roomResource.js
- nuve/nuveAPI/test/utils.js
Now relations between rooms and the erizoController where it is assigned are stored in the nuve database. This way, crashes in Nuve avoids service interruption.
> Saving ErizoController-Room relations in the database

- nuve/nuveAPI/cloudHandler.js
Nuve crashes when mongodb returns null in some case.
> Fix a crash when database returns null to Nuve

- nuve/nuveAPI/cloudHandler.js
- nuve/nuveAPI/mdb/erizoControllerRegistry.js
- nuve/nuveAPI/mdb/roomRegistry.js
- nuve/nuveAPI/resource/tokensResource.js
We were seeing problems with disappearing Erizo Controllers since latest changes in Nuve.
> Fix race conditions accessing db from Nuve

- erizo_controller/erizoAgent/launch.sh
With this PR we'll be able to run ErizoJS instances with special options. It can be used for instance to run node processes that will be inspected.
> Add options to ErizoJS processes (e.g. inspector)

- erizo/src/erizo/WebRtcConnection.cpp
This fixes an crash introduced in the latest PR.
> Fixes a crash in Erizo

- erizo_controller/erizoJS/erizoJSController.js
> Fixed a bug in createOffer params

- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/WebRtcConnection.h
- erizo/src/erizo/pipeline/Pipeline-inl.h
- erizo/src/erizo/pipeline/Pipeline.cpp
- erizo/src/erizo/pipeline/ServiceContext-inl.h
- erizo/src/erizo/rtp/RRGenerationHandler.cpp
- erizo/src/erizo/rtp/RtcpForwarder.cpp
- erizo/src/test/utils/Tools.h
This fixes a potential segmentation fault and makes the implementation of new Services less error prone.
@lodoyun found this potential issue and I've checked with this PR and it should help to avoid crashing anymore. Added some minor fixes to unexpected log lines and compilation warnings.
> Fix potential segmentation fault

- erizo/src/erizo/NiceConnection.cpp
Today I spent a lot of time testing the whole environment and NiceConnection crashed once because of this.
> Fixes a potential crash when closing NiceConnection

- extras/docker/Dockerfile
> Fixes docker run error

- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
- extras/basic_example/public/script.js
This will help us start adding Simulcast functionality to Erizo
> Add a beta client API to enable Simulcast

- erizo/src/erizo/Stats.cpp
- erizo/src/erizo/Stats.h
- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/WebRtcConnection.h
- erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp
- erizo/src/erizo/rtp/BandwidthEstimationHandler.h
- erizo/src/erizo/rtp/RtcpProcessorHandler.cpp
- erizo/src/erizo/rtp/RtcpProcessorHandler.h
- erizo/src/erizo/rtp/StatsHandler.cpp
- erizo/src/erizo/rtp/StatsHandler.h
- erizo/src/test/rtp/RtcpProcessorHandlerTest.cpp
- erizo/src/test/utils/Tools.h
- erizoAPI/WebRtcConnection.cc
- erizoAPI/WebRtcConnection.h
- erizo_controller/erizoJS/erizoJSController.js
- erizo_controller/test/utils.js
With this change it will be way too easier to add new stats. I've also made it asynchronous to be able to remove some mutex.
> Create stats using the new data structure

- extras/basic_example/public/quality_layers.js
Just a minor update to the quality layers page that disables animations and uses simple lines to reduce resource use.
None
> Fixed CPU use for the quality_layers page

- extras/basic_example/public/quality_layers.html
- extras/basic_example/public/quality_layers.js
Modified quality_layers basic_example page to better display temporal and spatial layers.
No changes in APIs
> Layers graph

- erizo/src/erizo/rtp/LayerBitrateCalculationHandler.h
- erizo/src/erizo/rtp/LayerDetectorHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.h
- erizo/src/erizo/rtp/QualityManager.cpp
- erizo/src/erizo/rtp/QualityManager.h
- erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp
- erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.h
- erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp
- erizo/src/erizo/rtp/SenderBandwidthEstimationHandler.h
- erizo/src/erizo/rtp/StatsHandler.h
- erizo/src/test/rtp/QualityManagerTest.cpp
- erizo/src/test/rtp/SenderBandwidthEstimationTest.cpp
- erizo_controller/erizoJS/erizoJSController.js
It updates Quality Manager to handle Padding enabling/disabling when switching spatial/temporal layers.
Not needed.
> Update Quality Manager to add Rtp Padding

- erizo/src/erizo/WebRtcConnection.cpp
We discovered some cases where we were updating stats from different threads concurrently. It could potentially cause a segmentation fault inside stats. This PR should fix it. 
Not needed.
> Resolve conflicts when updating stats from different threads

- extras/basic_example/public/quality_layers.html
- extras/basic_example/public/quality_layers.js
Updates quality_layer to add more streams in the graphs and avoid publishing/subscribing.
Not needed.
> Update charts in quaility_layers to show all streams

- extras/basic_example/public/quality_layers.html
- extras/basic_example/public/quality_layers.js
Adds tabs to quality_layers.html. It also resolves some issue when drawing graphs with no values and fixes some other minor issues.
Not needed.
> Add tabs and improve quality layers

- erizo/src/erizo/rtp/RtpSlideShowHandler.cpp
Fixed a possible out of bounds insert crash 
> Fixed out of bounds insert in slideshowhandler

- doc/server_api.md
Just a minnor fix to include the roles explanation post
*Add a detailed description of any change in the public APIs.*
[X] It includes documentation for these changes in `/doc`.
> Minor doc fix

- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.h
- erizo/src/erizo/rtp/RtpPaddingRemovalHandler.cpp
- erizo/src/erizo/rtp/RtpPaddingRemovalHandler.h
- erizo/src/erizo/rtp/RtpSlideShowHandler.cpp
Moved the padding removal to a new handler in the publisher
> Remove padding in publisher

- erizo/src/erizo/rtp/RtpPaddingRemovalHandler.cpp
- erizo/src/erizo/rtp/RtpPaddingRemovalHandler.h
- erizo_controller/erizoAgent/log4cxx.properties
Fixed padding removal in the publisher. It was not properly throwing away full padding packets
> Fixed padding remove implementation

- erizoAPI/WebRtcConnection.cc
This PR fixes a minor bug in erizoAPI stats method
No changes
> Fixed a minor bug in stats

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a template for issues reporting. It also adds extra information in PRs template.
> Added template for reporting issues

- doc/docker.md
- extras/docker/initDockerLicode.sh
Fixes problems with the docker image and Firefox by setting more network options
> Fixed Docker image for firefox adding network settings

- erizo_controller/erizoClient/src/views/AudioPlayer.js
- erizo_controller/erizoClient/src/views/Bar.js
- erizo_controller/erizoClient/src/views/VideoPlayer.js
Added a prefix to css classes in ErizoClient to avoid conflicts with apps that use Licode
> Added namespace to css classes in erizoClient

- extras/basic_example/public/index.html
- extras/basic_example/public/script.js
It updates Basic Example to stack videos horizontally, and stops getting access to the camera when connecting with `?onlySubscribe=1`.
Not needed.
> Stack video horizontallly in basic example

- spine/log4cxx.properties
- spine/nativeClient.js
Spine subscribers were not using the pipeline when used as subscribers because they had no sink. Added an OTM as a sink to enable the pipeline.
Also updated log file
> Add OTM to spine to enable pipeline

- spine/nativeClient.js
Fixes spine and make it work with nICEr too.
> Fix spine with new erizo api and nicer

- erizo/src/erizo/NicerConnection.cpp
- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/thread/IOWorker.cpp
- erizo/src/test/NicerConnectionTest.cpp
- spine/NativeStack.js
- spine/nativeClient.js
Fixes multiple issues that happened in NicerConnection when used by Spine.
Not needed.
> Fix issues when using Spine and NicerConnection

- erizo/src/erizo/DtlsTransport.cpp
- erizo/src/erizo/DtlsTransport.h
- erizo/src/erizo/NicerConnection.cpp
- erizo/src/erizo/rtp/RtcpNackGenerator.cpp
- erizo/src/erizo/thread/IOThreadPool.cpp
- erizo/src/erizo/thread/IOWorker.cpp
- erizo/src/erizo/thread/IOWorker.h
- erizo/src/erizo/thread/ThreadPool.cpp
- erizo/src/erizo/thread/Worker.cpp
- erizo/src/erizo/thread/Worker.h
- erizo_controller/erizoController/roomController.js
- erizo_controller/test/erizoController/roomController.js
Fix a timeout that happens sometimes when reloading a publisher.
Not needed.
> Fix erizoJS start and timeouts

- doc/custom_theme/base.html
- doc/custom_theme/toc.html
- doc/index.md
This PR fixes the table of contents of the documentation index page
> Fixed documentation index page

- erizo/src/erizo/NicerConnection.cpp
- erizo/src/erizo/lib/NicerInterface.cpp
- erizo/src/erizo/lib/NicerInterface.h
- erizo/src/test/NicerConnectionTest.cpp
Adds min_port and max_port support in NicerConnection.
Not needed
> Added input udp port range

- erizo_controller/erizoClient/src/views/Speaker.js
- erizo_controller/erizoClient/src/views/VideoPlayer.js
Reduce some lines of code in VideoPlayer and in Speaker (Erizo Client).
Not needed.
> Reduce some lines of code in Erizo Client

- erizo_controller/erizoClient/src/Events.js
- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoClient/src/Socket.js
- erizo_controller/erizoClient/src/Stream.js
- erizo_controller/erizoClient/src/utils/L.Base64.js
- erizo_controller/erizoClient/src/utils/L.Map.js
- erizo_controller/erizoClient/tools/compile.sh
- erizo_controller/erizoClient/tools/compileDebug.sh
- erizo_controller/erizoClient/tools/compilefc.sh
- erizo_controller/erizoClient/tools/compilefcDebug.sh
Refactor lots of lines within Room.js in Erizo Client to:
- Improve code readability.
- Reduce bugs.
- Make it easier to implement Single Peer Connection in a future.
> Refactor Room.js in Erizo Client

- erizo_controller/erizoClient/src/Socket.js
- erizo_controller/erizoClient/src/utils/L.Map.js
- erizo_controller/erizoClient/tools/compile.sh
- extras/basic_example/public/quality_layers.js
- spine/installSpine.sh
Fix some bugs that we introduced during the latest refactor tasks
Not needed.
> Fix some erizo client bugs since latest refactoring

- erizo_controller/installErizo_controller.sh
- nuve/installNuve.sh
- spine/installSpine.sh
Use a fixed version for log4js.
Not needed.
> Use older fixed log4js version

- erizo_controller/erizoClient/src/Connection.js
- erizo_controller/erizoClient/src/utils/L.Resizer.js
There were some minor issues since latest refactoring, related to Resizer and screensharing in Chrome.
Not needed.
> Fix issues with screensharing in Chrome and with Resizer

- extras/basic_example/public/script.js
Fix slideshow mode in basic example.
Not needed.
> Fix slideshow mode in basic example.

- erizo/src/erizo/MediaDefinitions.h
- erizo/src/erizo/rtp/LayerDetectorHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.h
- erizo/src/erizo/rtp/RtpVP8Parser.cpp
- erizo/src/erizo/rtp/RtpVP8Parser.h
Updates vp8 picture id when switching spatial qualities[] It needs and includes Unit Tests
Not needed.
> Updates vp8 picture id when switching spatial qualities

- .circleci/config.yml
- .dockerignore
- Dockerfile
Add another docker layer for dependencies to reduce build and deploy delays.
Not needed.
> Add another docker layer for dependencies

- erizo_controller/erizoClient/src/Socket.js
There are some cases where socket.io does not seem to work due to wrong transport behaviour. This code fixes it.
Not needed.
> Fix weird socket.io issues

- .circleci/config.yml
- .dockerignore
- Dockerfile
- utils/release.sh
Add a script to create releases and prereleases.
It also tries to reduce docker image size and build time by not including the .git folder.
Not needed.
> Create a release script and improve docker image

- LICENSE
- LICENSE.md
- README.md
The license has not changed. This PR uses the github template so it's easier to see in the repository.
> Use template for License

- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoClient/src/Stream.js
- spine/NativeStream.js
- spine/simpleNativeConnection.js
It fixes hasAudio and hasVideo to return always a boolean in the general case.
It just guarantees that hasAudio and hasVideo returns always a boolean.
> Fix hasAudio and hasVideo to return always a boolean.

- spine/simpleNativeConnection.js
Fix the way we configure the room which is used by Spine to connect to publishers and subscribers.
Not needed.
> Fix Spine to use different rooms

- erizo_controller/erizoClient/src/Events.js
> Fix stream attributes change events (#1037)

- erizo_controller/common/amqper.js
- erizo_controller/common/logger.js
- erizo_controller/erizoAgent/erizoAgent.js
- erizo_controller/erizoController/ecCloudHandler.js
- erizo_controller/erizoController/erizoController.js
- erizo_controller/erizoJS/erizoJS.js
- erizo_controller/erizoJS/erizoJSController.js
- erizo_controller/erizoJS/models/Publisher.js
- erizo_controller/test/erizoAgent/erizoAgent.js
- erizo_controller/test/erizoController/ecCloudHandler.js
- erizo_controller/test/erizoController/erizoController.js
- erizo_controller/test/erizoController/roomController.js
- erizo_controller/test/erizoJS/erizoJSController.js
- spine/nativeClient.js
Remove deprecation warning: 'GLOBAL' is deprecated, use 'global'
Not needed.
> Update global to lower case

- erizo/src/erizo/rtp/LayerDetectorHandler.cpp
- erizo/src/erizo/rtp/LayerDetectorHandler.h
- erizo/src/erizo/rtp/RtpH264Parser.cpp
- erizo/src/erizo/rtp/RtpH264Parser.h
- erizo/src/erizo/rtp/RtpSlideShowHandler.cpp
Add support to H264 codec in slideshow mode.
Not needed.
> Add support to slideshow mode in h264 videos

- erizo_controller/erizoClient/src/Socket.js
Fix Socket events in Erizo Client
Not needed.
> Fix Socket events in Erizo Client

- erizo_controller/erizoClient/lib/adapter.js
- erizo_controller/erizoClient/src/Connection.js
Update AdapterJS to v5.0.6
Not needed.
> Update AdapterJS to v5.0.6

- extras/docker/initDockerLicode.sh
fix for https://github.com/lynckia/licode/issues/919
> fix issue #919 docker crash on 2nd start

- feature-review/single-peer-connection.md
Updates the feature review for Single PeerConnection with some of the new ideas for the design.
> [FEATURE-REVIEW] Updated Single PeerConnection 

- erizo_controller/common/semanticSdp/MediaInfo.js
- erizo_controller/common/semanticSdp/SDPInfo.js
- erizo_controller/common/semanticSdp/Setup.js
Add setup to every mediastream and avoid to set ACTPASS in dtls role as default.
This will fix the p2p subscribe in Firefox, currently not working.
> Fix Firefox p2p subscribe currently not working

- erizo_controller/erizoClient/src/Socket.js
> Fix stream failed event not being correctly dispatched

- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoController/models/ErizoList.js
- erizo_controller/erizoController/roomController.js
Fix cases where we would not respect the limit of Erizos per Room
Not needed.
> Fix cases where we would not respect the limit of Erizos per Room

- erizo_controller/erizoClient/src/Stream.js
When creating integration tests I saw that p2p was broken. There were a couple of minor bugs in the recent code.
Not needed.
> Fix p2p connections

- erizo/generateEclipseProject.sh
little fix to generate Eclipse project
> fix geneateEclipseProject

- spine/installSpine.sh
Use env variable for gulp location
> Fix gulp path issue for installSpine.sh

- erizo_controller/erizoController/erizoController.js
when in p2p the roomcontroller does not exist
> Fix room removal in p2p

- erizo_controller/erizoClient/src/Stream.js
Fix unpublish logic in p2p mode
> Fix unpublish in p2p

- nuve/nuveAPI/mdb/serviceRegistry.js
- nuve/nuveAPI/resource/roomsResource.js
- nuve/nuveAPI/test/mdb/serviceRegistry.js
- nuve/nuveAPI/test/resource/roomsResource.js
- nuve/nuveAPI/test/utils.js
Same as https://github.com/lynckia/licode/pull/1064 but with unit tests
[X] It needs and includes Unit Tests
> Fix concurrency in Nuve create room

- .circleci/config.yml
This PR fixes some issue that happened during the previous days. These issues may prevent us to keep building and testing licode in CircleCI.
> Fix CircleCI scripts

- .gitignore
**GITIGNORE CLION IDE FILES**
This commit just adds clion config files to gitignore.
It has no code change and no additional tests are needed.
> Added clion configs to gitignore (.idea folder)

- nuve/installNuve.sh
Newer versions of google-closure-compiler need more changes to our compilation script. This sets an older version while we update the rest.
> Set a google-closure-compiler version

- erizo/src/third_party/nicer.cmake
Increment nICEr version to 1.3
> Increment nICEr version

- erizo/src/erizo/MediaStream.cpp
- erizo/src/erizo/MediaStream.h
- erizo/src/erizo/OneToManyProcessor.cpp
- erizo/src/erizo/OneToManyProcessor.h
- erizo/src/erizo/rtp/RtpPaddingGeneratorHandler.cpp
- erizoAPI/MediaStream.cc
Use random SSRCs for subscribers.
Not needed.
> Use random SSRCs for subscribers

- doc/client_api.md
Escapes HTML `<video>` tag using HTML entities.
> escape HTML tag

- erizoAPI/ExternalInput.cc
- erizoAPI/ExternalOutput.cc
- erizoAPI/MediaStream.cc
- erizoAPI/OneToManyProcessor.cc
- erizoAPI/OneToManyTranscoder.cc
- erizoAPI/SyntheticInput.cc
- erizoAPI/WebRtcConnection.cc
- scripts/installErizo.sh
Fix warnings when building node addon
Not needed.
> Fix warnings when building node addon

- erizo/src/erizo/rtp/QualityFilterHandler.cpp
- erizo_controller/erizoController/roomController.js
This fixes the issue in #1310. It should also fix #1366 
Not needed.
> Fix FIR check in QualityFilterHander

- erizo_controller/erizoClient/src/Room.js
Room logs often lack information needed to diagnose issues. This PR adds more info in warning and error logs, making it easier to track issues.
> Add more information to Room logs

- erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
I did not see a typo during the review of #1417
Not needed.
> Minor typo issue in setSimulcastLayersBitrate

- utils/release.sh
There was an issue by which we were not publishing new releases in Github since April. 
Not needed.
> Fix an issue with the release process

- erizo/src/erizo/DefaultValues.h
- erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp
- erizo/src/erizo/rtp/RtcpForwarder.h
- erizo/src/erizo/rtp/RtcpProcessor.h
This PR fixes #1434 
Not needed.
> Set hardcoded maxVideoBW to a higher value

- extras/basic_example/basicServer.js
Fix the way we get basic example port from the configuration
Not needed.
> Fix basic example port

- erizo/conanfile.txt
- scripts/installUbuntuDeps.sh
Update Boost library to version 1.70.
Not needed.
> Fix conan library by using latest version

- erizo/src/erizo/thread/ThreadPool.cpp
- erizo/src/erizo/thread/ThreadPool.h
- erizo/src/erizo/thread/Worker.cpp
- erizo/src/erizo/thread/Worker.h
- erizoAPI/ThreadPool.cc
- erizoAPI/ThreadPool.h
- erizo_controller/ROV/rovMetricsGatherer.js
- erizo_controller/erizoJS/erizoJSController.js
- erizo_controller/erizoJS/models/Client.js
This PR adds more info to ROV
Not needed.
> Add more metrics to ROV

- erizo_controller/erizoJS/erizoJSController.js
We were not getting the subscriber list properly.
> Fix the way we get subscribers for ErizoJS metrics

- doc/client_api.md
- erizo_controller/erizoClient/src/utils/ConnectionHelpers.js
This PR adds the documentation associated to PR #1468
[X] It includes documentation for these changes in `/doc`.
> Client API documentation for explaining MediaDevices.getDisplayMedia()

- erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp
We were not looking for REMBs or RRs after SRs in compound packets for BW estimation.
Not needed.
> Also search REMBs and RRs after SRs

- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/WebRtcConnection.h
- erizoAPI/WebRtcConnection.cc
- erizoAPI/WebRtcConnection.h
- erizo_controller/erizoJS/models/Connection.js
- erizo_controller/erizoJS/models/Node.js
Stats from WebRtcConnection will be added to the corresponding MediaStreams.
Not needed.
> Add WebRtcConnection stats to json

- doc/custom_theme/base.html
- doc/custom_theme/content.html
- doc/custom_theme/nav.html
- doc/custom_theme/toc.html
- mkdocs.yml
We have not being generating docs lately due to an issue with a new version of mkdocs which we did not support.
Not needed.
> Update docs to latest mkdocs version

- erizo_controller/common/semanticSdp/SimulcastInfo.js
This PR fixes an issue found by @yokots in #1481 
Not needed.
> Fix cloning of SimulcastInfos

- doc/custom_theme/base.html
- doc/custom_theme/nav.html
- doc/docker.md
The current compilation of docs with mkdocs points CSSs and JSs to the wrong path. I'm trying to fix them with this PR.
Not needed.
> Fix paths in docs and update info about docker

- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoJS/erizoJSController.js
- erizo_controller/erizoJS/models/Connection.js
This PR gives an option to send Offers from Erizo during subscription negotiation.
Not needed.
> Add option to send offer from erizo in subscriptions

- erizoAPI/package-lock.json
- erizo_controller/erizoClient/src/Erizo.js
- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoClient/src/Stream.js
- erizo_controller/erizoClient/src/utils/Base64.js
- erizo_controller/erizoClient/src/utils/Logger.js
- erizo_controller/erizoClient/src/views/AudioPlayer.js
- erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
- erizo_controller/package-lock.json
- extras/basic_example/package-lock.json
- nuve/package-lock.json
- package-lock.json
- spine/package-lock.json
This PR adds a valid `package-lock.json` file to cope with problems with dependencies of our required packages being updated.
It also fixes some indentation issues in erizoClient.
> Add package-lock and fix indentation issues

- scripts/installMacDeps.sh
Fixes an issue when installing the environment in Mac OS X.
Not needed.
> Fix MongoDB installation in mac

- erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
- erizo_controller/erizoController/models/Room.js
- erizo_controller/erizoJS/models/Connection.js
- extras/basic_example/public/script.js
Queue SDP negotiation messages in ErizoJS to avoid race conditions. It handle interlocks between client and ErizoJS queues.
Not needed.
> Queue negotiation messages in ErizoJS

- erizo_controller/erizoClient/src/utils/FunctionQueue.js
Fix an issue by which we were sending timeouts in cases where the negotiation was not blocked.
Not needed.
> Fix a wrong negotiation timeout

- scripts/installUbuntuDeps.sh
Fixes issue #1581 .
Not needed.
> Fix wrong check when installing on ubuntu

- extras/basic_example/basicServer.js
- scripts/licode_default.js
Fixes issue #1578 
Not needed.
> Use more configuration values in the Basic Example

- erizo_controller/erizoClient/src/ErizoConnectionManager.js
- erizo_controller/erizoClient/src/Room.js
- erizo_controller/erizoClient/src/Socket.js
- erizo_controller/erizoClient/src/Stream.js
- erizo_controller/erizoClient/src/utils/ConnectionHelpers.js
- erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/FcStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/PeerConnectionFsm.js
- erizo_controller/erizoController/erizoController.js
- extras/basic_example/public/script.js
This PR changes the way we structure the client's log lines. I also reduced the level of many of those logs from INFO to DEBUG, so it might affect how people usually track issues in the client. But I hope it will improve the way they detect them with all these changes.
Not needed.
> Give a better structure to client logs

- erizo_controller/erizoJS/models/Connection.js
It delays notifications about improved connection quality levels.
Not needed.
> Update timings to trigger connection quality levels

- scripts/installNuve.sh
This PR adds a way for users to install Nuve with predefined superservice credentials.
The idea would be to run it with a line like:
```bash
SERVID=5e78759edd5c1dede9ed9aac SERVKEY=33b ./installNuve.sh
```
Not needed.
> Let us use predefined superservice credentials

- extras/basic_example/public/script.js
This PR explicitly exposes global variables through `window`. This is helpful to use basicExample as a test in some environments.
> Make global variables part of window in basicExample

- erizo_controller/erizoJS/erizoJS.js
This PR allows better diagnose of rejected promises.
> Add more detail to unhandled rejected promises error log

- erizo/src/erizo/MediaStream.cpp
Add StreamPriority to main stats so it is gathered when calling `getStats()`
> Add stream priority to main stats

- erizoAPI/MediaStream.cc
I introduced a bug when solving conflicts between branches. This PR should fix it.
Not needed.
> Fix the way we set the stream priority in ErizoAPI

- erizo/src/erizo/SdpInfo.cpp
- erizo/src/erizo/WebRtcConnection.cpp
- erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp
- erizo/src/erizo/rtp/QualityFilterHandler.cpp
- erizo/src/erizo/rtp/RtpTrackMuteHandler.cpp
- erizo_controller/common/semanticSdp/SDPInfo.js
- erizo_controller/erizoJS/models/SessionDescription.js
- erizo_controller/erizoJS/models/WebRtcConnection.js
- erizo_controller/test/erizoJS/FullRtcPeerConnection.js
I keep testing things after having merged Unified Plan and I'm finding some minor issues of things that were not tested or that I broke when I merged some conflicts.
Not needed.
> Fix various issues related to unencrypted transport, stream priority and multiple publishers

- erizo_controller/erizoClient/src/ErizoConnectionManager.js
- erizo_controller/erizoClient/src/webrtc-stacks/BaseStack.js
- erizo_controller/erizoClient/src/webrtc-stacks/FirefoxStack.js
Fixes an issue when configuring simulcast layers. It specially affects Screensharing.
Not needed.
> Fix Simulcast Quality Layers

- erizo_controller/erizoJS/models/Client.js
- erizo_controller/erizoJS/models/RTCPeerConnection.js
- erizo_controller/test/erizoJS/RtcPeerConnection.js
This PR gives more information to the logs about negotiation.
Not needed.
> Fix some negotiation logs

- scripts/installUbuntuDeps.sh
> Fix conan builds

- erizo_controller/erizoJS/models/SessionDescription.js
- erizo_controller/erizoJS/models/WebRtcConnection.js
Use better variable names in SessionDescription
Not needed.
> Use better variable names in SessionDescription

- scripts/installUbuntuDeps.sh
Update conan version and remove manually added remotes. This should fix CI builds.
> Update conan version

- erizo_controller/erizoClient/src/Room.js
- scripts/installUbuntuDeps.sh
Connection Quality Level events were not being properly issued because of this bad check
> Fix ConnectionQualityLevel Events

- erizo/src/erizo/WebRtcConnection.cpp
Add `connectionQualityLevel` to stats logs.
> Add connectionQualityLevel to Stats

- erizo/src/erizo/WebRtcConnection.cpp
This PR properly marks packets as video or audio type before getting in the WebrtcConnection pipeline. We assumed that we already had the packet type in some of the handlers and this lead to some problems, particularly with the `BandwidthEstimationHandler` where video packet extensions were always used.
> Properly mark packet type when receiving packets in WebrtcConnection

- erizo/conanfile.txt
- erizo/src/erizo/WebRtcConnection.cpp
- scripts/installUbuntuDeps.sh
Update conan. Older versions did not work when downloading recipes anymore.
> Update conan to 1.51

- erizo/src/erizo/rtp/QualityFilterHandler.cpp
This PR remove duplicate spatial layer judgments.
Not needed.
> Remove duplicate spatial layer judgments

- erizo/src/erizo/WebRtcConnection.cpp
- scripts/installUbuntuDeps.sh
Update to the latest conan version to fix builds (again).
> Update to conan 1.52
